(in-package #:sb-vm)

(macrolet
    ((define-custom-vop (name &body clauses)
       (with-accessors ((name sb-simd-internals:instruction-record-name)
                        (vop sb-simd-internals:instruction-record-vop)
                        (argument-records sb-simd-internals:instruction-record-argument-records)
                        (result-records sb-simd-internals:instruction-record-result-records)
                        (cost sb-simd-internals:instruction-record-cost)
                        (encoding sb-simd-internals:instruction-record-encoding)
                        (instruction-set sb-simd-internals:instruction-record-instruction-set))
           (sb-simd-internals:find-function-record name)
         (assert (eq encoding :custom))
         (when (sb-simd-internals:instruction-set-available-p instruction-set)
           (labels ((find-clauses (key)
                      (remove key clauses :test-not #'eq :key #'first))
                    (find-clause (key)
                      (let ((found (find-clauses key)))
                        (assert (= 1 (length found)))
                        (rest (first found)))))
             `(sb-c:define-vop (,vop)
                (:translate ,vop)
                (:arg-types ,@(mapcar #'sb-simd-internals:value-record-primitive-type argument-records))
                (:result-types ,@(mapcar #'sb-simd-internals:value-record-primitive-type result-records))
                (:args
                 ,@(loop for arg in (find-clause :args)
                         for argument-record in argument-records
                         collect `(,@arg :scs ,(sb-simd-internals:value-record-scs argument-record))))
                ,@(find-clauses :info)
                ,@(find-clauses :temporary)
                (:results
                 ,@(loop for result in (find-clause :results)
                         for result-record in result-records
                         collect `(,@result :scs ,(sb-simd-internals:value-record-scs result-record))))
                (:generator ,cost ,@(find-clause :generator))))))))
#+x86-64
(progn
  ;; SSE
  (macrolet ((def (name cmp)
               `(define-custom-vop ,name
                    (:args (a :target tmp) (b))
                  (:temporary (:sc single-reg :from (:argument 0)) tmp)
                  (:results (dst))
                  (:generator
                   (unless (location= a tmp)
                     (inst xorps tmp tmp)
                     (inst movss tmp a))
                   (inst cmpss ,cmp tmp b)
                   (inst movq dst tmp)))))
    (def sb-simd-sse::two-arg-f32= :eq)
    (def sb-simd-sse::two-arg-f32/= :neq)
    (def sb-simd-sse::two-arg-f32< :lt)
    (def sb-simd-sse::two-arg-f32<= :le)
    (def sb-simd-sse::two-arg-f32> :nle)
    (def sb-simd-sse::two-arg-f32>= :nlt))
  (define-custom-vop sb-simd-sse::f32-from-s64
      (:args (src))
    (:results (dst))
    (:generator
     (inst xorps dst dst)
     (inst cvtsi2ss dst src)))
  (define-custom-vop sb-simd-sse::f32!-from-p128
      (:args (src :target dst))
    (:temporary (:sc single-sse-reg :from (:argument 0)) tmp)
    (:results (dst))
    (:generator
     (move tmp src)
     (inst xorps dst dst)
     (inst movss dst tmp)))
  ;; SSE2
  (macrolet ((def (name cmp)
               `(define-custom-vop ,name
                    (:args (a :target tmp) (b))
                  (:temporary (:sc single-reg :from (:argument 0)) tmp)
                  (:results (dst))
                  (:generator
                   (unless (location= a tmp)
                     (inst xorpd tmp tmp)
                     (inst movsd tmp a))
                   (inst cmpsd ,cmp tmp b)
                   (inst movq dst tmp)))))
    (def sb-simd-sse2::two-arg-f64= :eq)
    (def sb-simd-sse2::two-arg-f64/= :neq)
    (def sb-simd-sse2::two-arg-f64< :lt)
    (def sb-simd-sse2::two-arg-f64<= :le)
    (def sb-simd-sse2::two-arg-f64> :nle)
    (def sb-simd-sse2::two-arg-f64>= :nlt))
  (define-custom-vop sb-simd-sse2::f64-from-s64
      (:args (src))
    (:results (dst))
    (:generator
     (inst xorpd dst dst)
     (inst cvtsi2sd dst src)))
  (define-custom-vop sb-simd-sse2::f64!-from-p128
      (:args (src :target tmp))
    (:temporary (:sc double-sse-reg :from (:argument 0)) tmp)
    (:results (dst))
    (:generator
     (move tmp src)
     (inst xorpd dst dst)
     (inst movsd dst tmp)))
  ;; AVX
  (macrolet ((def (name cmp)
               `(define-custom-vop ,name
                    (:args (a :target tmp) (b))
                  (:temporary (:sc single-reg :from (:argument 0)) tmp)
                  (:results (dst))
                  (:generator
                   (unless (location= a tmp)
                     (inst vxorps tmp tmp tmp))
                   (inst vcmpss ,cmp tmp a b)
                   (inst vmovq dst tmp)))))
    (def sb-simd-avx::two-arg-f32= :eq)
    (def sb-simd-avx::two-arg-f32/= :neq)
    (def sb-simd-avx::two-arg-f32< :lt)
    (def sb-simd-avx::two-arg-f32<= :le)
    (def sb-simd-avx::two-arg-f32> :nle)
    (def sb-simd-avx::two-arg-f32>= :nlt))
  (macrolet ((def (name cmp)
               `(define-custom-vop ,name
                    (:args (a :target tmp) (b))
                  (:temporary (:sc single-reg :from (:argument 0)) tmp)
                  (:results (dst))
                  (:generator
                   (unless (location= a tmp)
                     (inst vxorpd tmp tmp tmp))
                   (inst vcmpsd ,cmp tmp a b)
                   (inst vmovq dst tmp)))))
    (def sb-simd-avx::two-arg-f64= :eq)
    (def sb-simd-avx::two-arg-f64/= :neq)
    (def sb-simd-avx::two-arg-f64< :lt)
    (def sb-simd-avx::two-arg-f64<= :le)
    (def sb-simd-avx::two-arg-f64> :nle)
    (def sb-simd-avx::two-arg-f64>= :nlt))
  (define-custom-vop sb-simd-avx::f32-from-s64
      (:args (src :to :save))
    (:results (dst))
    (:generator
     (inst vxorpd dst dst dst)
     (inst vcvtsi2ss dst dst src)))
  (define-custom-vop sb-simd-avx::f64-from-s64
      (:args (src :to :save))
    (:results (dst))
    (:generator
     (inst vxorpd dst dst dst)
     (inst vcvtsi2sd dst dst src)))
  (define-custom-vop sb-simd-avx::f32!-from-p128
      (:args (src :to :save))
    (:results (dst))
    (:generator
     (inst vxorps dst dst dst)
     (inst movss dst src)))
  (define-custom-vop sb-simd-avx::f32!-from-p256
      (:args (src :to :save))
    (:results (dst))
    (:generator
     (inst vxorps dst dst dst)
     (inst movss dst src)))
  (define-custom-vop sb-simd-avx::f64!-from-p128
      (:args (src :to :save))
    (:results (dst))
    (:generator
     (inst vxorpd dst dst dst)
     (inst movsd dst src)))
  (define-custom-vop sb-simd-avx::f64!-from-p256
      (:args (src :to :save))
    (:results (dst))
    (:generator
     (inst vxorpd dst dst dst)
     (inst movsd dst src)))
  (define-custom-vop sb-simd-avx512f::f32!-from-p512
      (:args (src :to :save))
    (:results (dst))
    (:generator
     (inst vxorps dst dst dst)
     (inst vmovss dst dst src)))
  (define-custom-vop sb-simd-avx512f::f64!-from-p512
      (:args (src :to :save))
    (:results (dst))
    (:generator
     (inst vxorpd dst dst dst)
     (inst vmovsd dst dst src)))
  ;; AVX-512F
  (macrolet ((def-f32 (name cmp)
               `(define-custom-vop ,name
                    (:args (a) (b))
                  (:temporary (:sc mask-reg) k)
                  (:results (dst))
                  (:generator
                   (inst vcmpps ,cmp k a b)
                   (inst vpmovm2d dst k))))
             (def-f64 (name cmp)
               `(define-custom-vop ,name
                    (:args (a) (b))
                  (:temporary (:sc mask-reg) k)
                  (:results (dst))
                  (:generator
                   (inst vcmppd ,cmp k a b)
                   (inst vpmovm2q dst k))))
             (def-i32 (name inst imm)
               `(define-custom-vop ,name
                    (:args (a) (b))
                  (:temporary (:sc mask-reg) k)
                  (:results (dst))
                  (:generator
                   (inst ,inst k a b ,imm)
                   (inst vpmovm2d dst k))))
             (def-i64 (name inst imm)
               `(define-custom-vop ,name
                    (:args (a) (b))
                  (:temporary (:sc mask-reg) k)
                  (:results (dst))
                  (:generator
                   (inst ,inst k a b ,imm)
                   (inst vpmovm2q dst k))))
             (def-i8 (name inst imm)
               `(define-custom-vop ,name
                    (:args (a) (b))
                  (:temporary (:sc mask-reg) k)
                  (:results (dst))
                  (:generator
                   (inst ,inst k a b ,imm)
                   (inst vpmovm2b dst k))))
             (def-i16 (name inst imm)
               `(define-custom-vop ,name
                    (:args (a) (b))
                  (:temporary (:sc mask-reg) k)
                  (:results (dst))
                  (:generator
                   (inst ,inst k a b ,imm)
                   (inst vpmovm2w dst k)))))
    (def-f32 sb-simd-avx512f::two-arg-f32.16=  :eq)
    (def-f32 sb-simd-avx512f::two-arg-f32.16/= :neq)
    (def-f32 sb-simd-avx512f::two-arg-f32.16<  :lt)
    (def-f32 sb-simd-avx512f::two-arg-f32.16<= :le)
    (def-f32 sb-simd-avx512f::two-arg-f32.16>  :gt)
    (def-f32 sb-simd-avx512f::two-arg-f32.16>= :ge)

    (def-f64 sb-simd-avx512f::two-arg-f64.8=  :eq)
    (def-f64 sb-simd-avx512f::two-arg-f64.8/= :neq)
    (def-f64 sb-simd-avx512f::two-arg-f64.8<  :lt)
    (def-f64 sb-simd-avx512f::two-arg-f64.8<= :le)
    (def-f64 sb-simd-avx512f::two-arg-f64.8>  :gt)
    (def-f64 sb-simd-avx512f::two-arg-f64.8>= :ge)

    (def-i32 sb-simd-avx512f::two-arg-s32.16=  vpcmpd  0)
    (def-i32 sb-simd-avx512f::two-arg-s32.16/= vpcmpd  4)
    (def-i32 sb-simd-avx512f::two-arg-s32.16<  vpcmpd  1)
    (def-i32 sb-simd-avx512f::two-arg-s32.16<= vpcmpd  2)
    (def-i32 sb-simd-avx512f::two-arg-s32.16>  vpcmpd  6)
    (def-i32 sb-simd-avx512f::two-arg-s32.16>= vpcmpd  5)

    (def-i32 sb-simd-avx512f::two-arg-u32.16=  vpcmpud 0)
    (def-i32 sb-simd-avx512f::two-arg-u32.16/= vpcmpud 4)
    (def-i32 sb-simd-avx512f::two-arg-u32.16<  vpcmpud 1)
    (def-i32 sb-simd-avx512f::two-arg-u32.16<= vpcmpud 2)
    (def-i32 sb-simd-avx512f::two-arg-u32.16>  vpcmpud 6)
    (def-i32 sb-simd-avx512f::two-arg-u32.16>= vpcmpud 5)

    (def-i64 sb-simd-avx512f::two-arg-s64.8=  vpcmpq  0)
    (def-i64 sb-simd-avx512f::two-arg-s64.8/= vpcmpq  4)
    (def-i64 sb-simd-avx512f::two-arg-s64.8<  vpcmpq  1)
    (def-i64 sb-simd-avx512f::two-arg-s64.8<= vpcmpq  2)
    (def-i64 sb-simd-avx512f::two-arg-s64.8>  vpcmpq  6)
    (def-i64 sb-simd-avx512f::two-arg-s64.8>= vpcmpq  5)

    (def-i64 sb-simd-avx512f::two-arg-u64.8=  vpcmpuq 0)
    (def-i64 sb-simd-avx512f::two-arg-u64.8/= vpcmpuq 4)
    (def-i64 sb-simd-avx512f::two-arg-u64.8<  vpcmpuq 1)
    (def-i64 sb-simd-avx512f::two-arg-u64.8<= vpcmpuq 2)
    (def-i64 sb-simd-avx512f::two-arg-u64.8>  vpcmpuq 6)
    (def-i64 sb-simd-avx512f::two-arg-u64.8>= vpcmpuq 5)

    (def-i8 sb-simd-avx512bw::two-arg-s8.64=  vpcmpb  0)
    (def-i8 sb-simd-avx512bw::two-arg-s8.64/= vpcmpb  4)
    (def-i8 sb-simd-avx512bw::two-arg-s8.64<  vpcmpb  1)
    (def-i8 sb-simd-avx512bw::two-arg-s8.64<= vpcmpb  2)
    (def-i8 sb-simd-avx512bw::two-arg-s8.64>  vpcmpb  6)
    (def-i8 sb-simd-avx512bw::two-arg-s8.64>= vpcmpb  5)

    (def-i8 sb-simd-avx512bw::two-arg-u8.64=  vpcmpub 0)
    (def-i8 sb-simd-avx512bw::two-arg-u8.64/= vpcmpub 4)
    (def-i8 sb-simd-avx512bw::two-arg-u8.64<  vpcmpub 1)
    (def-i8 sb-simd-avx512bw::two-arg-u8.64<= vpcmpub 2)
    (def-i8 sb-simd-avx512bw::two-arg-u8.64>  vpcmpub 6)
    (def-i8 sb-simd-avx512bw::two-arg-u8.64>= vpcmpub 5)

    (def-i16 sb-simd-avx512bw::two-arg-s16.32=  vpcmpw  0)
    (def-i16 sb-simd-avx512bw::two-arg-s16.32/= vpcmpw  4)
    (def-i16 sb-simd-avx512bw::two-arg-s16.32<  vpcmpw  1)
    (def-i16 sb-simd-avx512bw::two-arg-s16.32<= vpcmpw  2)
    (def-i16 sb-simd-avx512bw::two-arg-s16.32>  vpcmpw  6)
    (def-i16 sb-simd-avx512bw::two-arg-s16.32>= vpcmpw  5)

    (def-i16 sb-simd-avx512bw::two-arg-u16.32=  vpcmpuw 0)
    (def-i16 sb-simd-avx512bw::two-arg-u16.32/= vpcmpuw 4)
    (def-i16 sb-simd-avx512bw::two-arg-u16.32<  vpcmpuw 1)
    (def-i16 sb-simd-avx512bw::two-arg-u16.32<= vpcmpuw 2)
    (def-i16 sb-simd-avx512bw::two-arg-u16.32>  vpcmpuw 6)
    (def-i16 sb-simd-avx512bw::two-arg-u16.32>= vpcmpuw 5))

  (macrolet ((def-mask-cmp-f (name inst cmp)
               `(define-custom-vop ,name
                    (:args (a) (b))
                  (:results (dst))
                  (:generator
                   (inst ,inst ,cmp dst a b))))
             (def-mask-cmp-i (name inst imm)
               `(define-custom-vop ,name
                    (:args (a) (b))
                  (:results (dst))
                  (:generator
                   (inst ,inst dst a b ,imm)))))
    ;; AVX-512F mask comparisons
    (def-mask-cmp-f sb-simd-avx512f::two-arg-f32.16-mask=  vcmpps :eq)
    (def-mask-cmp-f sb-simd-avx512f::two-arg-f32.16-mask/= vcmpps :neq)
    (def-mask-cmp-f sb-simd-avx512f::two-arg-f32.16-mask<  vcmpps :lt)
    (def-mask-cmp-f sb-simd-avx512f::two-arg-f32.16-mask<= vcmpps :le)
    (def-mask-cmp-f sb-simd-avx512f::two-arg-f32.16-mask>  vcmpps :gt)
    (def-mask-cmp-f sb-simd-avx512f::two-arg-f32.16-mask>= vcmpps :ge)

    (def-mask-cmp-f sb-simd-avx512f::two-arg-f64.8-mask=   vcmppd :eq)
    (def-mask-cmp-f sb-simd-avx512f::two-arg-f64.8-mask/=  vcmppd :neq)
    (def-mask-cmp-f sb-simd-avx512f::two-arg-f64.8-mask<   vcmppd :lt)
    (def-mask-cmp-f sb-simd-avx512f::two-arg-f64.8-mask<=  vcmppd :le)
    (def-mask-cmp-f sb-simd-avx512f::two-arg-f64.8-mask>   vcmppd :gt)
    (def-mask-cmp-f sb-simd-avx512f::two-arg-f64.8-mask>=  vcmppd :ge)

    (def-mask-cmp-i sb-simd-avx512f::two-arg-s32.16-mask=  vpcmpd  0)
    (def-mask-cmp-i sb-simd-avx512f::two-arg-s32.16-mask/= vpcmpd  4)
    (def-mask-cmp-i sb-simd-avx512f::two-arg-s32.16-mask<  vpcmpd  1)
    (def-mask-cmp-i sb-simd-avx512f::two-arg-s32.16-mask<= vpcmpd  2)
    (def-mask-cmp-i sb-simd-avx512f::two-arg-s32.16-mask>  vpcmpd  6)
    (def-mask-cmp-i sb-simd-avx512f::two-arg-s32.16-mask>= vpcmpd  5)

    (def-mask-cmp-i sb-simd-avx512f::two-arg-u32.16-mask=  vpcmpud 0)
    (def-mask-cmp-i sb-simd-avx512f::two-arg-u32.16-mask/= vpcmpud 4)
    (def-mask-cmp-i sb-simd-avx512f::two-arg-u32.16-mask<  vpcmpud 1)
    (def-mask-cmp-i sb-simd-avx512f::two-arg-u32.16-mask<= vpcmpud 2)
    (def-mask-cmp-i sb-simd-avx512f::two-arg-u32.16-mask>  vpcmpud 6)
    (def-mask-cmp-i sb-simd-avx512f::two-arg-u32.16-mask>= vpcmpud 5)

    (def-mask-cmp-i sb-simd-avx512f::two-arg-s64.8-mask=   vpcmpq  0)
    (def-mask-cmp-i sb-simd-avx512f::two-arg-s64.8-mask/=  vpcmpq  4)
    (def-mask-cmp-i sb-simd-avx512f::two-arg-s64.8-mask<   vpcmpq  1)
    (def-mask-cmp-i sb-simd-avx512f::two-arg-s64.8-mask<=  vpcmpq  2)
    (def-mask-cmp-i sb-simd-avx512f::two-arg-s64.8-mask>   vpcmpq  6)
    (def-mask-cmp-i sb-simd-avx512f::two-arg-s64.8-mask>=  vpcmpq  5)

    (def-mask-cmp-i sb-simd-avx512f::two-arg-u64.8-mask=   vpcmpuq 0)
    (def-mask-cmp-i sb-simd-avx512f::two-arg-u64.8-mask/=  vpcmpuq 4)
    (def-mask-cmp-i sb-simd-avx512f::two-arg-u64.8-mask<   vpcmpuq 1)
    (def-mask-cmp-i sb-simd-avx512f::two-arg-u64.8-mask<=  vpcmpuq 2)
    (def-mask-cmp-i sb-simd-avx512f::two-arg-u64.8-mask>   vpcmpuq 6)
    (def-mask-cmp-i sb-simd-avx512f::two-arg-u64.8-mask>=  vpcmpuq 5)

    ;; AVX-512BW mask comparisons
    (def-mask-cmp-i sb-simd-avx512bw::two-arg-s8.64-mask=  vpcmpb  0)
    (def-mask-cmp-i sb-simd-avx512bw::two-arg-s8.64-mask/= vpcmpb  4)
    (def-mask-cmp-i sb-simd-avx512bw::two-arg-s8.64-mask<  vpcmpb  1)
    (def-mask-cmp-i sb-simd-avx512bw::two-arg-s8.64-mask<= vpcmpb  2)
    (def-mask-cmp-i sb-simd-avx512bw::two-arg-s8.64-mask>  vpcmpb  6)
    (def-mask-cmp-i sb-simd-avx512bw::two-arg-s8.64-mask>= vpcmpb  5)

    (def-mask-cmp-i sb-simd-avx512bw::two-arg-u8.64-mask=  vpcmpub 0)
    (def-mask-cmp-i sb-simd-avx512bw::two-arg-u8.64-mask/= vpcmpub 4)
    (def-mask-cmp-i sb-simd-avx512bw::two-arg-u8.64-mask<  vpcmpub 1)
    (def-mask-cmp-i sb-simd-avx512bw::two-arg-u8.64-mask<= vpcmpub 2)
    (def-mask-cmp-i sb-simd-avx512bw::two-arg-u8.64-mask>  vpcmpub 6)
    (def-mask-cmp-i sb-simd-avx512bw::two-arg-u8.64-mask>= vpcmpub 5)

    (def-mask-cmp-i sb-simd-avx512bw::two-arg-s16.32-mask=  vpcmpw  0)
    (def-mask-cmp-i sb-simd-avx512bw::two-arg-s16.32-mask/= vpcmpw  4)
    (def-mask-cmp-i sb-simd-avx512bw::two-arg-s16.32-mask<  vpcmpw  1)
    (def-mask-cmp-i sb-simd-avx512bw::two-arg-s16.32-mask<= vpcmpw  2)
    (def-mask-cmp-i sb-simd-avx512bw::two-arg-s16.32-mask>  vpcmpw  6)
    (def-mask-cmp-i sb-simd-avx512bw::two-arg-s16.32-mask>= vpcmpw  5)

    (def-mask-cmp-i sb-simd-avx512bw::two-arg-u16.32-mask=  vpcmpuw 0)
    (def-mask-cmp-i sb-simd-avx512bw::two-arg-u16.32-mask/= vpcmpuw 4)
    (def-mask-cmp-i sb-simd-avx512bw::two-arg-u16.32-mask<  vpcmpuw 1)
    (def-mask-cmp-i sb-simd-avx512bw::two-arg-u16.32-mask<= vpcmpuw 2)
    (def-mask-cmp-i sb-simd-avx512bw::two-arg-u16.32-mask>  vpcmpuw 6)
    (def-mask-cmp-i sb-simd-avx512bw::two-arg-u16.32-mask>= vpcmpuw 5))

  ;; AVX-512F masked arithmetic
  (macrolet ((def-masked-z-binop (name inst)
               `(define-custom-vop ,name
                    (:args (mask) (a) (b))
                  (:results (dst))
                  (:generator
                   (inst ,inst dst a b mask :z))))
             (def-masked-binop (name move-inst inst)
               `(define-custom-vop ,name
                    (:args (mask) (default :target dst) (a :to :save) (b :to :save))
                  (:results (dst))
                  (:generator
                   (unless (location= dst default)
                     (inst ,move-inst dst default))
                   (inst ,inst dst a b mask 0))))
             (def-masked-z-unop (name inst)
               `(define-custom-vop ,name
                    (:args (mask) (a))
                  (:results (dst))
                  (:generator
                   (inst ,inst dst a mask :z))))
             (def-masked-unop (name move-inst inst)
               `(define-custom-vop ,name
                    (:args (mask) (default :target dst) (a :to :save))
                  (:results (dst))
                  (:generator
                   (unless (location= dst default)
                     (inst ,move-inst dst default))
                   (inst ,inst dst a mask 0)))))
    ;; f32.16
    (def-masked-z-binop sb-simd-avx512f::f32.16-masked-z+     vaddps-masked)
    (def-masked-z-binop sb-simd-avx512f::f32.16-masked-z-     vsubps-masked)
    (def-masked-z-binop sb-simd-avx512f::f32.16-masked-z*     vmulps-masked)
    (def-masked-z-binop sb-simd-avx512f::f32.16-masked-z/     vdivps-masked)
    (def-masked-z-binop sb-simd-avx512f::f32.16-masked-z-max  vmaxps-masked)
    (def-masked-z-binop sb-simd-avx512f::f32.16-masked-z-min  vminps-masked)
    (def-masked-z-unop  sb-simd-avx512f::f32.16-masked-z-sqrt vsqrtps-masked)

    (def-masked-binop   sb-simd-avx512f::f32.16-masked+     vmovaps vaddps-masked)
    (def-masked-binop   sb-simd-avx512f::f32.16-masked-     vmovaps vsubps-masked)
    (def-masked-binop   sb-simd-avx512f::f32.16-masked*     vmovaps vmulps-masked)
    (def-masked-binop   sb-simd-avx512f::f32.16-masked/     vmovaps vdivps-masked)
    (def-masked-binop   sb-simd-avx512f::f32.16-masked-max  vmovaps vmaxps-masked)
    (def-masked-binop   sb-simd-avx512f::f32.16-masked-min  vmovaps vminps-masked)
    (def-masked-unop    sb-simd-avx512f::f32.16-masked-sqrt vmovaps vsqrtps-masked)

    ;; f64.8
    (def-masked-z-binop sb-simd-avx512f::f64.8-masked-z+     vaddpd-masked)
    (def-masked-z-binop sb-simd-avx512f::f64.8-masked-z-     vsubpd-masked)
    (def-masked-z-binop sb-simd-avx512f::f64.8-masked-z*     vmulpd-masked)
    (def-masked-z-binop sb-simd-avx512f::f64.8-masked-z/     vdivpd-masked)
    (def-masked-z-binop sb-simd-avx512f::f64.8-masked-z-max  vmaxpd-masked)
    (def-masked-z-binop sb-simd-avx512f::f64.8-masked-z-min  vminpd-masked)
    (def-masked-z-unop  sb-simd-avx512f::f64.8-masked-z-sqrt vsqrtpd-masked)

    (def-masked-binop   sb-simd-avx512f::f64.8-masked+     vmovapd vaddpd-masked)
    (def-masked-binop   sb-simd-avx512f::f64.8-masked-     vmovapd vsubpd-masked)
    (def-masked-binop   sb-simd-avx512f::f64.8-masked*     vmovapd vmulpd-masked)
    (def-masked-binop   sb-simd-avx512f::f64.8-masked/     vmovapd vdivpd-masked)
    (def-masked-binop   sb-simd-avx512f::f64.8-masked-max  vmovapd vmaxpd-masked)
    (def-masked-binop   sb-simd-avx512f::f64.8-masked-min  vmovapd vminpd-masked)
    (def-masked-unop    sb-simd-avx512f::f64.8-masked-sqrt vmovapd vsqrtpd-masked)

    ;; u32.16
    (def-masked-z-binop sb-simd-avx512f::u32.16-masked-z+      vpaddd-masked)
    (def-masked-z-binop sb-simd-avx512f::u32.16-masked-z-      vpsubd-masked)
    (def-masked-z-binop sb-simd-avx512f::u32.16-masked-z*      vpmulld-masked)
    (def-masked-z-binop sb-simd-avx512f::u32.16-masked-z-and   vpandd-masked)
    (def-masked-z-binop sb-simd-avx512f::u32.16-masked-z-andc1 vpandnd-masked)
    (def-masked-z-binop sb-simd-avx512f::u32.16-masked-z-or    vpord-masked)
    (def-masked-z-binop sb-simd-avx512f::u32.16-masked-z-xor   vpxord-masked)

    (def-masked-binop   sb-simd-avx512f::u32.16-masked+      vmovdqa32 vpaddd-masked)
    (def-masked-binop   sb-simd-avx512f::u32.16-masked-      vmovdqa32 vpsubd-masked)
    (def-masked-binop   sb-simd-avx512f::u32.16-masked*      vmovdqa32 vpmulld-masked)
    (def-masked-binop   sb-simd-avx512f::u32.16-masked-and   vmovdqa32 vpandd-masked)
    (def-masked-binop   sb-simd-avx512f::u32.16-masked-andc1 vmovdqa32 vpandnd-masked)
    (def-masked-binop   sb-simd-avx512f::u32.16-masked-or    vmovdqa32 vpord-masked)
    (def-masked-binop   sb-simd-avx512f::u32.16-masked-xor   vmovdqa32 vpxord-masked)

    ;; s32.16
    (def-masked-z-binop sb-simd-avx512f::s32.16-masked-z+      vpaddd-masked)
    (def-masked-z-binop sb-simd-avx512f::s32.16-masked-z-      vpsubd-masked)
    (def-masked-z-binop sb-simd-avx512f::s32.16-masked-z*      vpmulld-masked)
    (def-masked-z-binop sb-simd-avx512f::s32.16-masked-z-and   vpandd-masked)
    (def-masked-z-binop sb-simd-avx512f::s32.16-masked-z-andc1 vpandnd-masked)
    (def-masked-z-binop sb-simd-avx512f::s32.16-masked-z-or    vpord-masked)
    (def-masked-z-binop sb-simd-avx512f::s32.16-masked-z-xor   vpxord-masked)

    (def-masked-binop   sb-simd-avx512f::s32.16-masked+      vmovdqa32 vpaddd-masked)
    (def-masked-binop   sb-simd-avx512f::s32.16-masked-      vmovdqa32 vpsubd-masked)
    (def-masked-binop   sb-simd-avx512f::s32.16-masked*      vmovdqa32 vpmulld-masked)
    (def-masked-binop   sb-simd-avx512f::s32.16-masked-and   vmovdqa32 vpandd-masked)
    (def-masked-binop   sb-simd-avx512f::s32.16-masked-andc1 vmovdqa32 vpandnd-masked)
    (def-masked-binop   sb-simd-avx512f::s32.16-masked-or    vmovdqa32 vpord-masked)
    (def-masked-binop   sb-simd-avx512f::s32.16-masked-xor   vmovdqa32 vpxord-masked)

    ;; u64.8
    (def-masked-z-binop sb-simd-avx512f::u64.8-masked-z+      vpaddq-masked)
    (def-masked-z-binop sb-simd-avx512f::u64.8-masked-z-      vpsubq-masked)
    (def-masked-z-binop sb-simd-avx512f::u64.8-masked-z-and   vpandq-masked)
    (def-masked-z-binop sb-simd-avx512f::u64.8-masked-z-andc1 vpandnq-masked)
    (def-masked-z-binop sb-simd-avx512f::u64.8-masked-z-or    vporq-masked)
    (def-masked-z-binop sb-simd-avx512f::u64.8-masked-z-xor   vpxorq-masked)

    (def-masked-binop   sb-simd-avx512f::u64.8-masked+      vmovdqa64 vpaddq-masked)
    (def-masked-binop   sb-simd-avx512f::u64.8-masked-      vmovdqa64 vpsubq-masked)
    (def-masked-binop   sb-simd-avx512f::u64.8-masked-and   vmovdqa64 vpandq-masked)
    (def-masked-binop   sb-simd-avx512f::u64.8-masked-andc1 vmovdqa64 vpandnq-masked)
    (def-masked-binop   sb-simd-avx512f::u64.8-masked-or    vmovdqa64 vporq-masked)
    (def-masked-binop   sb-simd-avx512f::u64.8-masked-xor   vmovdqa64 vpxorq-masked)

    ;; s64.8
    (def-masked-z-binop sb-simd-avx512f::s64.8-masked-z+      vpaddq-masked)
    (def-masked-z-binop sb-simd-avx512f::s64.8-masked-z-      vpsubq-masked)
    (def-masked-z-binop sb-simd-avx512f::s64.8-masked-z-and   vpandq-masked)
    (def-masked-z-binop sb-simd-avx512f::s64.8-masked-z-andc1 vpandnq-masked)
    (def-masked-z-binop sb-simd-avx512f::s64.8-masked-z-or    vporq-masked)
    (def-masked-z-binop sb-simd-avx512f::s64.8-masked-z-xor   vpxorq-masked)

    (def-masked-binop   sb-simd-avx512f::s64.8-masked+      vmovdqa64 vpaddq-masked)
    (def-masked-binop   sb-simd-avx512f::s64.8-masked-      vmovdqa64 vpsubq-masked)
    (def-masked-binop   sb-simd-avx512f::s64.8-masked-and   vmovdqa64 vpandq-masked)
    (def-masked-binop   sb-simd-avx512f::s64.8-masked-andc1 vmovdqa64 vpandnq-masked)
    (def-masked-binop   sb-simd-avx512f::s64.8-masked-or    vmovdqa64 vporq-masked)
    (def-masked-binop   sb-simd-avx512f::s64.8-masked-xor   vmovdqa64 vpxorq-masked))

  (define-custom-vop sb-simd-avx512f::f32.16-blend
      (:args (a) (b) (mask))
    (:temporary (:sc mask-reg) k)
    (:temporary (:sc single-avx512-reg) mask-reg tmp)
    (:temporary (:sc int-avx512-reg) zero)
    (:results (dst))
    (:generator
     (inst vpxorq zero zero zero)
     (inst vpcmpd k mask zero 1)
     (inst vpmovm2d mask-reg k)
     (inst vandps tmp b mask-reg)
     (inst vandnps dst mask-reg a)
     (inst vorps dst dst tmp)))

  (define-custom-vop sb-simd-avx512f::f64.8-blend
      (:args (a) (b) (mask))
    (:temporary (:sc mask-reg) k)
    (:temporary (:sc double-avx512-reg) mask-reg tmp)
    (:temporary (:sc int-avx512-reg) zero)
    (:results (dst))
    (:generator
     (inst vpxorq zero zero zero)
     (inst vpcmpq k mask zero 1)
     (inst vpmovm2q mask-reg k)
     (inst vandpd tmp b mask-reg)
     (inst vandnpd dst mask-reg a)
     (inst vorpd dst dst tmp)))

  (macrolet ((def-blend (name)
               `(define-custom-vop ,name
                    (:args (a) (b) (mask))
                  (:temporary (:sc mask-reg) k)
                  (:temporary (:sc int-avx512-reg) zero tmp mask-reg)
                  (:results (dst))
                  (:generator
                   (inst vpxorq zero zero zero)
                   (inst vpcmpb k mask zero 1)
                   (inst vpmovm2b mask-reg k)
                   (inst vpandd tmp b mask-reg)
                   (inst vpandnd dst mask-reg a)
                   (inst vpord dst dst tmp)))))
    (def-blend sb-simd-avx512f::u32.16-blend)
    (def-blend sb-simd-avx512f::s32.16-blend)
    (def-blend sb-simd-avx512f::u64.8-blend)
    (def-blend sb-simd-avx512f::s64.8-blend)
    (def-blend sb-simd-avx512bw::u8.64-blend)
    (def-blend sb-simd-avx512bw::s8.64-blend)
    (def-blend sb-simd-avx512bw::u16.32-blend)
    (def-blend sb-simd-avx512bw::s16.32-blend))

  (macrolet ((def-not (name)
               `(define-custom-vop ,name
                    (:args (a))
                  (:results (dst))
                  (:generator
                   (inst vpternlogd dst a a #x55)))))
    (def-not sb-simd-avx512f::f32.16-not)
    (def-not sb-simd-avx512f::f64.8-not)
    (def-not sb-simd-avx512f::u32.16-not)
    (def-not sb-simd-avx512f::u64.8-not)
    (def-not sb-simd-avx512f::s32.16-not)
    (def-not sb-simd-avx512f::s64.8-not)
    (def-not sb-simd-avx512bw::u8.64-not)
    (def-not sb-simd-avx512bw::u16.32-not)
    (def-not sb-simd-avx512bw::s8.64-not)
    (def-not sb-simd-avx512bw::s16.32-not)
    (def-not sb-simd-avx512fp16::f16.32-not))

  (eval-when (:compile-toplevel :load-toplevel :execute)
    (sb-ext:without-package-locks
      (flet ((register-masked-move (name prefix opcode-from opcode-to w &optional (opcode-prefix #x0f))
               (let* ((sym-asm (intern (string name) "SB-X86-64-ASM"))
                      (sym-vm (intern (string name) "SB-VM"))
                      (fn (lambda (segment dst src mask &optional (zeroing 0))
                            (let ((mask-num (cond ((integerp mask) mask)
                                                  ((sb-x86-64-asm::k-register-p mask) (sb-x86-64-asm::reg-num mask))
                                                  (t (error "Invalid mask ~S" mask))))
                                  (z-num (if (or (eq zeroing :z) (eql zeroing 1)) 1 0)))
                              (cond ((sb-x86-64-asm::xmm-register-p dst)
                                     (sb-x86-64-asm::emit-avx512-inst segment src dst prefix opcode-from
                                                       :opcode-prefix opcode-prefix
                                                       :w w
                                                       :aaa mask-num
                                                       :z z-num
                                                       :disp-n (sb-x86-64-asm::full-vector-disp-n dst)))
                                    (t
                                     (aver (sb-x86-64-asm::xmm-register-p src))
                                     (sb-x86-64-asm::emit-avx512-inst segment dst src prefix opcode-to
                                                       :opcode-prefix opcode-prefix
                                                       :w w
                                                       :aaa mask-num
                                                       :z 0
                                                       :disp-n (sb-x86-64-asm::full-vector-disp-n src))))))))
                 (setf (gethash sym-asm sb-assem::*inst-encoder*) fn)
                 (setf (gethash sym-vm sb-assem::*inst-encoder*) fn)))
             (register-masked-compress (name prefix opcode w)
               (let* ((sym-asm (intern (string name) "SB-X86-64-ASM"))
                      (sym-vm  (intern (string name) "SB-VM"))
                      (fn (lambda (segment dst src mask &optional (zeroing 0))
                            (let ((mask-num (cond ((integerp mask) mask)
                                                  ((sb-x86-64-asm::k-register-p mask) (sb-x86-64-asm::reg-num mask))
                                                  (t (error "Invalid mask ~S" mask))))
                                  (z-num (if (or (eq zeroing :z) (eql zeroing 1)) 1 0)))
                              (sb-x86-64-asm::emit-avx512-inst segment dst src prefix opcode
                                                               :opcode-prefix #x0f38
                                                               :w w
                                                               :aaa mask-num
                                                               :z z-num
                                                               :disp-n (if (zerop w) 4 8))))))
                 (setf (gethash sym-asm sb-assem::*inst-encoder*) fn)
                 (setf (gethash sym-vm sb-assem::*inst-encoder*) fn)))
             (register-masked-expand (name prefix opcode w)
               (let* ((sym-asm (intern (string name) "SB-X86-64-ASM"))
                      (sym-vm  (intern (string name) "SB-VM"))
                      (fn (lambda (segment dst src mask &optional (zeroing 0))
                            (let ((mask-num (cond ((integerp mask) mask)
                                                  ((sb-x86-64-asm::k-register-p mask) (sb-x86-64-asm::reg-num mask))
                                                  (t (error "Invalid mask ~S" mask))))
                                  (z-num (if (or (eq zeroing :z) (eql zeroing 1)) 1 0)))
                              (sb-x86-64-asm::emit-avx512-inst segment src dst prefix opcode
                                                               :opcode-prefix #x0f38
                                                               :w w
                                                               :aaa mask-num
                                                               :z z-num
                                                               :disp-n (if (zerop w) 4 8))))))
                 (setf (gethash sym-asm sb-assem::*inst-encoder*) fn)
                 (setf (gethash sym-vm sb-assem::*inst-encoder*) fn))))
        (register-masked-move 'vmovups-masked   nil  #x10 #x11 0)
        (register-masked-move 'vmovupd-masked   #x66 #x10 #x11 1)
        (register-masked-move 'vmovdqu32-masked #xf3 #x6f #x7f 0)
        (register-masked-move 'vmovdqu64-masked #xf3 #x6f #x7f 1)
        (register-masked-compress 'vcompressps-masked  #x66 #x8a 0)
        (register-masked-compress 'vcompresspd-masked  #x66 #x8a 1)
        (register-masked-compress 'vpcompressd-masked  #x66 #x8b 0)
        (register-masked-compress 'vpcompressq-masked  #x66 #x8b 1)
        (register-masked-expand   'vexpandps-masked    #x66 #x88 0)
        (register-masked-expand   'vexpandpd-masked    #x66 #x88 1)
        (register-masked-expand   'vpexpandd-masked    #x66 #x89 0)
        (register-masked-expand   'vpexpandq-masked    #x66 #x89 1))))

  (macrolet
      ((def-masked-vref-vops (type-name reg-sc stack-sc mask-name mask-sc mnemonic move-inst vec-name bytes-per-element)
         (declare (ignore stack-sc mask-sc))
         (let* ((pkg (find-package "SB-SIMD-AVX512F"))
                (load-z-name       (sb-simd-internals:mksym pkg "%" type-name "-LOAD-MASKED-Z"))
                (load-z-c-name     (sb-simd-internals:mksym pkg "%" type-name "-LOAD-MASKED-Z-C"))
                (sap-load-z-name   (sb-simd-internals:mksym pkg "%" type-name "-SAP-REF-MASKED-Z"))
                (sap-load-z-c-name (sb-simd-internals:mksym pkg "%" type-name "-SAP-REF-MASKED-Z-C"))

                (load-m-name       (sb-simd-internals:mksym pkg "%" type-name "-LOAD-MASKED"))
                (load-m-c-name     (sb-simd-internals:mksym pkg "%" type-name "-LOAD-MASKED-C"))
                (sap-load-m-name   (sb-simd-internals:mksym pkg "%" type-name "-SAP-REF-MASKED"))
                (sap-load-m-c-name (sb-simd-internals:mksym pkg "%" type-name "-SAP-REF-MASKED-C"))

                (store-name         (sb-simd-internals:mksym pkg "%" type-name "-STORE-MASKED"))
                (store-c-name       (sb-simd-internals:mksym pkg "%" type-name "-STORE-MASKED-C"))
                (sap-store-name     (sb-simd-internals:mksym pkg "%SET-" type-name "-SAP-REF-MASKED"))
                (sap-store-c-name   (sb-simd-internals:mksym pkg "%SET-" type-name "-SAP-REF-MASKED-C"))

                (val-rec  (sb-simd-internals:find-value-record (sb-simd-internals:mksym pkg type-name)))
                (vec-rec  (sb-simd-internals:find-value-record (sb-simd-internals:mksym pkg vec-name)))
                (mask-rec (sb-simd-internals:find-value-record (sb-simd-internals:mksym pkg mask-name)))

                (value-type (sb-simd-internals:value-record-type val-rec))
                (value-primitive-type (sb-simd-internals:value-record-primitive-type val-rec))
                (value-scs `(,reg-sc))

                (vector-type (sb-simd-internals:value-record-type vec-rec))
                (vector-primitive-type (sb-simd-internals:value-record-primitive-type vec-rec))

                (mask-type (sb-simd-internals:value-record-type mask-rec))
                (mask-primitive-type (sb-simd-internals:value-record-primitive-type mask-rec))

                (displacement
                  (multiple-value-bind (lo hi)
                      (displacement-bounds other-pointer-lowtag (* 8 bytes-per-element) vector-data-offset)
                    `(integer ,lo ,hi))))
           (multiple-value-bind (index-scs scale)
               (if (>= bytes-per-element (ash 1 n-fixnum-tag-bits))
                   (values '(any-reg signed-reg unsigned-reg) `(index-scale ,bytes-per-element index))
                   (values '(signed-reg unsigned-reg) bytes-per-element))
             `(progn
                ;; 1. Zeroing Load VOP (Array)
                (defknown ,load-z-name (,mask-type ,vector-type index ,displacement)
                    (values ,value-type &optional)
                    (always-translatable)
                  :overwrite-fndb-silently t)
                (define-vop (,load-z-name)
                  (:translate ,load-z-name)
                  (:args (mask :scs (mask-reg))
                         (vector :scs (descriptor-reg))
                         (index :scs ,index-scs))
                  (:info addend)
                  (:arg-types ,mask-primitive-type ,vector-primitive-type positive-fixnum (:constant ,displacement))
                  (:results (result :scs ,value-scs))
                  (:result-types ,value-primitive-type)
                  (:generator 2
                    (let ((ea (ea (+ (* vector-data-offset n-word-bytes)
                                     (* addend ,bytes-per-element)
                                     (- other-pointer-lowtag))
                                  vector index ,scale)))
                      (inst ,mnemonic result ea mask :z))))
                (define-vop (,load-z-c-name)
                  (:translate ,load-z-name)
                  (:args (mask :scs (mask-reg))
                         (vector :scs (descriptor-reg)))
                  (:info index addend)
                  (:arg-types ,mask-primitive-type ,vector-primitive-type (:constant low-index) (:constant ,displacement))
                  (:results (result :scs ,value-scs))
                  (:result-types ,value-primitive-type)
                  (:generator 1
                    (let ((ea (ea (+ (* vector-data-offset n-word-bytes)
                                     (* ,bytes-per-element (+ index addend))
                                     (- other-pointer-lowtag))
                                  vector)))
                      (inst ,mnemonic result ea mask :z))))

                ;; 2. Zeroing Load VOP (SAP)
                (defknown ,sap-load-z-name (,mask-type sb-alien:system-area-pointer index ,displacement)
                    (values ,value-type &optional)
                    (always-translatable)
                  :overwrite-fndb-silently t)
                (define-vop (,sap-load-z-name)
                  (:translate ,sap-load-z-name)
                  (:args (mask :scs (mask-reg))
                         (sap :scs (sap-reg))
                         (index :scs ,index-scs))
                  (:info addend)
                  (:arg-types ,mask-primitive-type sb-alien:system-area-pointer positive-fixnum (:constant ,displacement))
                  (:results (result :scs ,value-scs))
                  (:result-types ,value-primitive-type)
                  (:generator 2
                    (let ((ea (ea (* addend ,bytes-per-element) sap index ,scale)))
                      (inst ,mnemonic result ea mask :z))))
                (define-vop (,sap-load-z-c-name)
                  (:translate ,sap-load-z-name)
                  (:args (mask :scs (mask-reg))
                         (sap :scs (sap-reg)))
                  (:info index addend)
                  (:arg-types ,mask-primitive-type sb-alien:system-area-pointer (:constant low-index) (:constant ,displacement))
                  (:results (result :scs ,value-scs))
                  (:result-types ,value-primitive-type)
                  (:generator 1
                    (let ((ea (ea (* ,bytes-per-element (+ index addend)) sap)))
                      (inst ,mnemonic result ea mask :z))))

                ;; 3. Merging Load VOP (Array)
                (defknown ,load-m-name (,mask-type ,value-type ,vector-type index ,displacement)
                    (values ,value-type &optional)
                    (always-translatable)
                  :overwrite-fndb-silently t)
                (define-vop (,load-m-name)
                  (:translate ,load-m-name)
                  (:args (mask :scs (mask-reg))
                         (default :scs ,value-scs :target result)
                         (vector :scs (descriptor-reg))
                         (index :scs ,index-scs))
                  (:info addend)
                  (:arg-types ,mask-primitive-type ,value-primitive-type ,vector-primitive-type positive-fixnum (:constant ,displacement))
                  (:results (result :scs ,value-scs))
                  (:result-types ,value-primitive-type)
                  (:generator 2
                    (unless (location= result default)
                      (inst ,move-inst result default))
                    (let ((ea (ea (+ (* vector-data-offset n-word-bytes)
                                     (* addend ,bytes-per-element)
                                     (- other-pointer-lowtag))
                                  vector index ,scale)))
                      (inst ,mnemonic result ea mask 0))))
                (define-vop (,load-m-c-name)
                  (:translate ,load-m-name)
                  (:args (mask :scs (mask-reg))
                         (default :scs ,value-scs :target result)
                         (vector :scs (descriptor-reg)))
                  (:info index addend)
                  (:arg-types ,mask-primitive-type ,value-primitive-type ,vector-primitive-type (:constant low-index) (:constant ,displacement))
                  (:results (result :scs ,value-scs))
                  (:result-types ,value-primitive-type)
                  (:generator 1
                    (unless (location= result default)
                      (inst ,move-inst result default))
                    (let ((ea (ea (+ (* vector-data-offset n-word-bytes)
                                     (* ,bytes-per-element (+ index addend))
                                     (- other-pointer-lowtag))
                                  vector)))
                      (inst ,mnemonic result ea mask 0))))

                ;; 4. Merging Load VOP (SAP)
                (defknown ,sap-load-m-name (,mask-type ,value-type sb-alien:system-area-pointer index ,displacement)
                    (values ,value-type &optional)
                    (always-translatable)
                  :overwrite-fndb-silently t)
                (define-vop (,sap-load-m-name)
                  (:translate ,sap-load-m-name)
                  (:args (mask :scs (mask-reg))
                         (default :scs ,value-scs :target result)
                         (sap :scs (sap-reg))
                         (index :scs ,index-scs))
                  (:info addend)
                  (:arg-types ,mask-primitive-type ,value-primitive-type sb-alien:system-area-pointer positive-fixnum (:constant ,displacement))
                  (:results (result :scs ,value-scs))
                  (:result-types ,value-primitive-type)
                  (:generator 2
                    (let ((ea (ea (* addend ,bytes-per-element) sap index ,scale)))
                      (unless (location= result default)
                        (inst ,move-inst result default))
                      (inst ,mnemonic result ea mask 0))))
                (define-vop (,sap-load-m-c-name)
                  (:translate ,sap-load-m-name)
                  (:args (mask :scs (mask-reg))
                         (default :scs ,value-scs :target result)
                         (sap :scs (sap-reg)))
                  (:info index addend)
                  (:arg-types ,mask-primitive-type ,value-primitive-type sb-alien:system-area-pointer (:constant low-index) (:constant ,displacement))
                  (:results (result :scs ,value-scs))
                  (:result-types ,value-primitive-type)
                  (:generator 1
                    (let ((ea (ea (* ,bytes-per-element (+ index addend)) sap)))
                      (unless (location= result default)
                        (inst ,move-inst result default))
                      (inst ,mnemonic result ea mask 0))))

                ;; 5. Masked Store VOP (Array)
                (defknown ,store-name (,mask-type ,value-type ,vector-type index ,displacement)
                    (values ,value-type &optional)
                    (always-translatable)
                  :overwrite-fndb-silently t)
                (define-vop (,store-name)
                  (:translate ,store-name)
                  (:args (mask :scs (mask-reg))
                         (value :scs ,value-scs :target result)
                         (vector :scs (descriptor-reg))
                         (index :scs ,index-scs))
                  (:info addend)
                  (:arg-types ,mask-primitive-type ,value-primitive-type ,vector-primitive-type positive-fixnum (:constant ,displacement))
                  (:results (result :scs ,value-scs))
                  (:result-types ,value-primitive-type)
                  (:generator 2
                    (let ((ea (ea (+ (* vector-data-offset n-word-bytes)
                                     (* addend ,bytes-per-element)
                                     (- other-pointer-lowtag))
                                  vector index ,scale)))
                      (inst ,mnemonic ea value mask)
                      (move result value))))
                (define-vop (,store-c-name)
                  (:translate ,store-name)
                  (:args (mask :scs (mask-reg))
                         (value :scs ,value-scs :target result)
                         (vector :scs (descriptor-reg)))
                  (:info index addend)
                  (:arg-types ,mask-primitive-type ,value-primitive-type ,vector-primitive-type (:constant low-index) (:constant ,displacement))
                  (:results (result :scs ,value-scs))
                  (:result-types ,value-primitive-type)
                  (:generator 1
                    (let ((ea (ea (+ (* vector-data-offset n-word-bytes)
                                     (* ,bytes-per-element (+ index addend))
                                     (- other-pointer-lowtag))
                                  vector)))
                      (inst ,mnemonic ea value mask)
                      (move result value))))

                ;; 6. Masked Store VOP (SAP)
                (defknown ,sap-store-name (,mask-type ,value-type sb-alien:system-area-pointer index ,displacement)
                    (values ,value-type &optional)
                    (always-translatable)
                  :overwrite-fndb-silently t)
                (define-vop (,sap-store-name)
                  (:translate ,sap-store-name)
                  (:args (mask :scs (mask-reg))
                         (value :scs ,value-scs :target result)
                         (sap :scs (sap-reg))
                         (index :scs ,index-scs))
                  (:info addend)
                  (:arg-types ,mask-primitive-type ,value-primitive-type sb-alien:system-area-pointer positive-fixnum (:constant ,displacement))
                  (:results (result :scs ,value-scs))
                  (:result-types ,value-primitive-type)
                  (:generator 2
                    (let ((ea (ea (* addend ,bytes-per-element) sap index ,scale)))
                      (inst ,mnemonic ea value mask)
                      (move result value))))
                (define-vop (,sap-store-c-name)
                  (:translate ,sap-store-name)
                  (:args (mask :scs (mask-reg))
                         (value :scs ,value-scs :target result)
                         (sap :scs (sap-reg)))
                  (:info index addend)
                  (:arg-types ,mask-primitive-type ,value-primitive-type sb-alien:system-area-pointer (:constant low-index) (:constant ,displacement))
                  (:results (result :scs ,value-scs))
                  (:result-types ,value-primitive-type)
                  (:generator 1
                    (let ((ea (ea (* ,bytes-per-element (+ index addend)) sap)))
                      (inst ,mnemonic ea value mask)
                      (move result value)))))))))

    (def-masked-vref-vops f32.16 single-avx512-reg single-avx512-stack m32.16 unsigned-reg vmovups-masked   vmovaps f32vec 4)
    (def-masked-vref-vops f64.8  double-avx512-reg double-avx512-stack m64.8  unsigned-reg vmovupd-masked   vmovapd f64vec 8)
    (def-masked-vref-vops u32.16 int-avx512-reg    int-avx512-stack    m32.16 unsigned-reg vmovdqu32-masked vmovdqa32 u32vec 4)
    (def-masked-vref-vops s32.16 int-avx512-reg    int-avx512-stack    m32.16 unsigned-reg vmovdqu32-masked vmovdqa32 s32vec 4)
    (def-masked-vref-vops u64.8  int-avx512-reg    int-avx512-stack    m64.8  unsigned-reg vmovdqu64-masked vmovdqa64 u64vec 8)
    (def-masked-vref-vops s64.8  int-avx512-reg    int-avx512-stack    m64.8  unsigned-reg vmovdqu64-masked vmovdqa64 s64vec 8))

    ;; Register compress and expand VOPs
    (macrolet ((def-compress-z (name inst)
                 `(define-custom-vop ,name
                      (:args (mask) (a))
                    (:results (dst))
                    (:generator
                     (inst ,inst dst a mask :z))))
               (def-compress (name move-inst inst)
                 `(define-custom-vop ,name
                      (:args (mask) (default :target dst) (a :to :save))
                    (:results (dst))
                    (:generator
                     (unless (location= dst default)
                       (inst ,move-inst dst default))
                     (inst ,inst dst a mask 0))))
               (def-expand-z (name inst)
                 `(define-custom-vop ,name
                      (:args (mask) (a))
                    (:results (dst))
                    (:generator
                     (inst ,inst dst a mask :z))))
               (def-expand (name move-inst inst)
                 `(define-custom-vop ,name
                      (:args (mask) (default :target dst) (a :to :save))
                    (:results (dst))
                    (:generator
                     (unless (location= dst default)
                       (inst ,move-inst dst default))
                     (inst ,inst dst a mask 0)))))
      ;; f32.16
      (def-compress-z sb-simd-avx512f::f32.16-compress-z vcompressps-masked)
      (def-compress   sb-simd-avx512f::f32.16-compress   vmovaps vcompressps-masked)
      (def-expand-z   sb-simd-avx512f::f32.16-expand-z   vexpandps-masked)
      (def-expand     sb-simd-avx512f::f32.16-expand     vmovaps vexpandps-masked)

      ;; f64.8
      (def-compress-z sb-simd-avx512f::f64.8-compress-z  vcompresspd-masked)
      (def-compress   sb-simd-avx512f::f64.8-compress    vmovapd vcompresspd-masked)
      (def-expand-z   sb-simd-avx512f::f64.8-expand-z    vexpandpd-masked)
      (def-expand     sb-simd-avx512f::f64.8-expand      vmovapd vexpandpd-masked)

      ;; u32.16
      (def-compress-z sb-simd-avx512f::u32.16-compress-z vpcompressd-masked)
      (def-compress   sb-simd-avx512f::u32.16-compress   vmovdqa32 vpcompressd-masked)
      (def-expand-z   sb-simd-avx512f::u32.16-expand-z   vpexpandd-masked)
      (def-expand     sb-simd-avx512f::u32.16-expand     vmovdqa32 vpexpandd-masked)

      ;; s32.16
      (def-compress-z sb-simd-avx512f::s32.16-compress-z vpcompressd-masked)
      (def-compress   sb-simd-avx512f::s32.16-compress   vmovdqa32 vpcompressd-masked)
      (def-expand-z   sb-simd-avx512f::s32.16-expand-z   vpexpandd-masked)
      (def-expand     sb-simd-avx512f::s32.16-expand     vmovdqa32 vpexpandd-masked)

      ;; u64.8
      (def-compress-z sb-simd-avx512f::u64.8-compress-z  vpcompressq-masked)
      (def-compress   sb-simd-avx512f::u64.8-compress    vmovdqa64 vpcompressq-masked)
      (def-expand-z   sb-simd-avx512f::u64.8-expand-z    vpexpandq-masked)
      (def-expand     sb-simd-avx512f::u64.8-expand      vmovdqa64 vpexpandq-masked)

      ;; s64.8
      (def-compress-z sb-simd-avx512f::s64.8-compress-z  vpcompressq-masked)
      (def-compress   sb-simd-avx512f::s64.8-compress    vmovdqa64 vpcompressq-masked)
      (def-expand-z   sb-simd-avx512f::s64.8-expand-z    vpexpandq-masked)
      (def-expand     sb-simd-avx512f::s64.8-expand      vmovdqa64 vpexpandq-masked))

    ;; Memory compress and expand VOPs
    (macrolet
        ((def-compress-expand-memory-vops (type-name reg-sc mask-name compress-inst expand-inst move-inst vec-name bytes-per-element)
           (let* ((pkg (find-package "SB-SIMD-AVX512F"))
                  ;; Compress store (Array)
                  (c-store-name         (sb-simd-internals:mksym pkg "%" type-name "-COMPRESS-STORE"))
                  (c-store-c-name       (sb-simd-internals:mksym pkg "%" type-name "-COMPRESS-STORE-C"))
                  ;; Compress store (SAP)
                  (c-sap-store-name     (sb-simd-internals:mksym pkg "%" type-name "-SAP-COMPRESS-STORE"))
                  (c-sap-store-c-name   (sb-simd-internals:mksym pkg "%" type-name "-SAP-COMPRESS-STORE-C"))

                  ;; Expand load zeroing (Array)
                  (e-load-z-name        (sb-simd-internals:mksym pkg "%" type-name "-EXPAND-LOAD-Z"))
                  (e-load-z-c-name      (sb-simd-internals:mksym pkg "%" type-name "-EXPAND-LOAD-Z-C"))
                  ;; Expand load zeroing (SAP)
                  (e-sap-load-z-name    (sb-simd-internals:mksym pkg "%" type-name "-SAP-EXPAND-LOAD-Z"))
                  (e-sap-load-z-c-name  (sb-simd-internals:mksym pkg "%" type-name "-SAP-EXPAND-LOAD-Z-C"))

                  ;; Expand load merging (Array)
                  (e-load-m-name        (sb-simd-internals:mksym pkg "%" type-name "-EXPAND-LOAD"))
                  (e-load-m-c-name      (sb-simd-internals:mksym pkg "%" type-name "-EXPAND-LOAD-C"))
                  ;; Expand load merging (SAP)
                  (e-sap-load-m-name    (sb-simd-internals:mksym pkg "%" type-name "-SAP-EXPAND-LOAD"))
                  (e-sap-load-m-c-name  (sb-simd-internals:mksym pkg "%" type-name "-SAP-EXPAND-LOAD-C"))

                  (val-rec  (sb-simd-internals:find-value-record (sb-simd-internals:mksym pkg type-name)))
                  (vec-rec  (sb-simd-internals:find-value-record (sb-simd-internals:mksym pkg vec-name)))
                  (mask-rec (sb-simd-internals:find-value-record (sb-simd-internals:mksym pkg mask-name)))

                  (value-type (sb-simd-internals:value-record-type val-rec))
                  (value-primitive-type (sb-simd-internals:value-record-primitive-type val-rec))
                  (value-scs `(,reg-sc))

                  (vector-type (sb-simd-internals:value-record-type vec-rec))
                  (vector-primitive-type (sb-simd-internals:value-record-primitive-type vec-rec))

                  (mask-type (sb-simd-internals:value-record-type mask-rec))
                  (mask-primitive-type (sb-simd-internals:value-record-primitive-type mask-rec))

                  (displacement
                    (multiple-value-bind (lo hi)
                        (displacement-bounds other-pointer-lowtag (* 8 bytes-per-element) vector-data-offset)
                      `(integer ,lo ,hi))))
             (multiple-value-bind (index-scs scale)
                 (if (>= bytes-per-element (ash 1 n-fixnum-tag-bits))
                     (values '(any-reg signed-reg unsigned-reg) `(index-scale ,bytes-per-element index))
                     (values '(signed-reg unsigned-reg) bytes-per-element))
               `(progn
                  ;; 1. Compress Store VOP (Array)
                  (defknown ,c-store-name (,mask-type ,value-type ,vector-type index ,displacement)
                      (values ,value-type &optional)
                      (always-translatable)
                    :overwrite-fndb-silently t)
                  (define-vop (,c-store-name)
                    (:translate ,c-store-name)
                    (:args (mask :scs (mask-reg))
                           (value :scs ,value-scs :target result)
                           (vector :scs (descriptor-reg))
                           (index :scs ,index-scs))
                    (:info addend)
                    (:arg-types ,mask-primitive-type ,value-primitive-type ,vector-primitive-type positive-fixnum (:constant ,displacement))
                    (:results (result :scs ,value-scs))
                    (:result-types ,value-primitive-type)
                    (:generator 2
                      (let ((ea (ea (+ (* vector-data-offset n-word-bytes)
                                       (* addend ,bytes-per-element)
                                       (- other-pointer-lowtag))
                                    vector index ,scale)))
                        (inst ,compress-inst ea value mask 0)
                        (move result value))))
                  (define-vop (,c-store-c-name)
                    (:translate ,c-store-name)
                    (:args (mask :scs (mask-reg))
                           (value :scs ,value-scs :target result)
                           (vector :scs (descriptor-reg)))
                    (:info index addend)
                    (:arg-types ,mask-primitive-type ,value-primitive-type ,vector-primitive-type (:constant low-index) (:constant ,displacement))
                    (:results (result :scs ,value-scs))
                    (:result-types ,value-primitive-type)
                    (:generator 1
                      (let ((ea (ea (+ (* vector-data-offset n-word-bytes)
                                       (* ,bytes-per-element (+ index addend))
                                       (- other-pointer-lowtag))
                                    vector)))
                        (inst ,compress-inst ea value mask 0)
                        (move result value))))

                  ;; 2. Compress Store VOP (SAP)
                  (defknown ,c-sap-store-name (,mask-type ,value-type sb-alien:system-area-pointer index ,displacement)
                      (values ,value-type &optional)
                      (always-translatable)
                    :overwrite-fndb-silently t)
                  (define-vop (,c-sap-store-name)
                    (:translate ,c-sap-store-name)
                    (:args (mask :scs (mask-reg))
                           (value :scs ,value-scs :target result)
                           (sap :scs (sap-reg))
                           (index :scs ,index-scs))
                    (:info addend)
                    (:arg-types ,mask-primitive-type ,value-primitive-type sb-alien:system-area-pointer positive-fixnum (:constant ,displacement))
                    (:results (result :scs ,value-scs))
                    (:result-types ,value-primitive-type)
                    (:generator 2
                      (let ((ea (ea (* addend ,bytes-per-element) sap index ,scale)))
                        (inst ,compress-inst ea value mask 0)
                        (move result value))))
                  (define-vop (,c-sap-store-c-name)
                    (:translate ,c-sap-store-name)
                    (:args (mask :scs (mask-reg))
                           (value :scs ,value-scs :target result)
                           (sap :scs (sap-reg)))
                    (:info index addend)
                    (:arg-types ,mask-primitive-type ,value-primitive-type sb-alien:system-area-pointer (:constant low-index) (:constant ,displacement))
                    (:results (result :scs ,value-scs))
                    (:result-types ,value-primitive-type)
                    (:generator 1
                      (let ((ea (ea (* ,bytes-per-element (+ index addend)) sap)))
                        (inst ,compress-inst ea value mask 0)
                        (move result value))))

                  ;; 3. Expand Load Zeroing VOP (Array)
                  (defknown ,e-load-z-name (,mask-type ,vector-type index ,displacement)
                      (values ,value-type &optional)
                      (always-translatable)
                    :overwrite-fndb-silently t)
                  (define-vop (,e-load-z-name)
                    (:translate ,e-load-z-name)
                    (:args (mask :scs (mask-reg))
                           (vector :scs (descriptor-reg))
                           (index :scs ,index-scs))
                    (:info addend)
                    (:arg-types ,mask-primitive-type ,vector-primitive-type positive-fixnum (:constant ,displacement))
                    (:results (result :scs ,value-scs))
                    (:result-types ,value-primitive-type)
                    (:generator 2
                      (let ((ea (ea (+ (* vector-data-offset n-word-bytes)
                                       (* addend ,bytes-per-element)
                                       (- other-pointer-lowtag))
                                    vector index ,scale)))
                        (inst ,expand-inst result ea mask 1))))
                  (define-vop (,e-load-z-c-name)
                    (:translate ,e-load-z-name)
                    (:args (mask :scs (mask-reg))
                           (vector :scs (descriptor-reg)))
                    (:info index addend)
                    (:arg-types ,mask-primitive-type ,vector-primitive-type (:constant low-index) (:constant ,displacement))
                    (:results (result :scs ,value-scs))
                    (:result-types ,value-primitive-type)
                    (:generator 1
                      (let ((ea (ea (+ (* vector-data-offset n-word-bytes)
                                       (* ,bytes-per-element (+ index addend))
                                       (- other-pointer-lowtag))
                                    vector)))
                        (inst ,expand-inst result ea mask 1))))

                  ;; 4. Expand Load Zeroing VOP (SAP)
                  (defknown ,e-sap-load-z-name (,mask-type sb-alien:system-area-pointer index ,displacement)
                      (values ,value-type &optional)
                      (always-translatable)
                    :overwrite-fndb-silently t)
                  (define-vop (,e-sap-load-z-name)
                    (:translate ,e-sap-load-z-name)
                    (:args (mask :scs (mask-reg))
                           (sap :scs (sap-reg))
                           (index :scs ,index-scs))
                    (:info addend)
                    (:arg-types ,mask-primitive-type sb-alien:system-area-pointer positive-fixnum (:constant ,displacement))
                    (:results (result :scs ,value-scs))
                    (:result-types ,value-primitive-type)
                    (:generator 2
                      (let ((ea (ea (* addend ,bytes-per-element) sap index ,scale)))
                        (inst ,expand-inst result ea mask 1))))
                  (define-vop (,e-sap-load-z-c-name)
                    (:translate ,e-sap-load-z-name)
                    (:args (mask :scs (mask-reg))
                           (sap :scs (sap-reg)))
                    (:info index addend)
                    (:arg-types ,mask-primitive-type sb-alien:system-area-pointer (:constant low-index) (:constant ,displacement))
                    (:results (result :scs ,value-scs))
                    (:result-types ,value-primitive-type)
                    (:generator 1
                      (let ((ea (ea (* ,bytes-per-element (+ index addend)) sap)))
                        (inst ,expand-inst result ea mask 1))))

                  ;; 5. Expand Load Merging VOP (Array)
                  (defknown ,e-load-m-name (,mask-type ,value-type ,vector-type index ,displacement)
                      (values ,value-type &optional)
                      (always-translatable)
                    :overwrite-fndb-silently t)
                  (define-vop (,e-load-m-name)
                    (:translate ,e-load-m-name)
                    (:args (mask :scs (mask-reg))
                           (default :scs ,value-scs :target result)
                           (vector :scs (descriptor-reg))
                           (index :scs ,index-scs))
                    (:info addend)
                    (:arg-types ,mask-primitive-type ,value-primitive-type ,vector-primitive-type positive-fixnum (:constant ,displacement))
                    (:results (result :scs ,value-scs))
                    (:result-types ,value-primitive-type)
                    (:generator 2
                      (unless (location= result default)
                        (inst ,move-inst result default))
                      (let ((ea (ea (+ (* vector-data-offset n-word-bytes)
                                       (* addend ,bytes-per-element)
                                       (- other-pointer-lowtag))
                                    vector index ,scale)))
                        (inst ,expand-inst result ea mask 0))))
                  (define-vop (,e-load-m-c-name)
                    (:translate ,e-load-m-name)
                    (:args (mask :scs (mask-reg))
                           (default :scs ,value-scs :target result)
                           (vector :scs (descriptor-reg)))
                    (:info index addend)
                    (:arg-types ,mask-primitive-type ,value-primitive-type ,vector-primitive-type (:constant low-index) (:constant ,displacement))
                    (:results (result :scs ,value-scs))
                    (:result-types ,value-primitive-type)
                    (:generator 1
                      (unless (location= result default)
                        (inst ,move-inst result default))
                      (let ((ea (ea (+ (* vector-data-offset n-word-bytes)
                                       (* ,bytes-per-element (+ index addend))
                                       (- other-pointer-lowtag))
                                    vector)))
                        (inst ,expand-inst result ea mask 0))))

                  ;; 6. Expand Load Merging VOP (SAP)
                  (defknown ,e-sap-load-m-name (,mask-type ,value-type sb-alien:system-area-pointer index ,displacement)
                      (values ,value-type &optional)
                      (always-translatable)
                    :overwrite-fndb-silently t)
                  (define-vop (,e-sap-load-m-name)
                    (:translate ,e-sap-load-m-name)
                    (:args (mask :scs (mask-reg))
                           (default :scs ,value-scs :target result)
                           (sap :scs (sap-reg))
                           (index :scs ,index-scs))
                    (:info addend)
                    (:arg-types ,mask-primitive-type ,value-primitive-type sb-alien:system-area-pointer positive-fixnum (:constant ,displacement))
                    (:results (result :scs ,value-scs))
                    (:result-types ,value-primitive-type)
                    (:generator 2
                      (unless (location= result default)
                        (inst ,move-inst result default))
                      (let ((ea (ea (* addend ,bytes-per-element) sap index ,scale)))
                        (inst ,expand-inst result ea mask 0))))
                  (define-vop (,e-sap-load-m-c-name)
                    (:translate ,e-sap-load-m-name)
                    (:args (mask :scs (mask-reg))
                           (default :scs ,value-scs :target result)
                           (sap :scs (sap-reg)))
                    (:info index addend)
                    (:arg-types ,mask-primitive-type ,value-primitive-type sb-alien:system-area-pointer (:constant low-index) (:constant ,displacement))
                    (:results (result :scs ,value-scs))
                    (:result-types ,value-primitive-type)
                    (:generator 1
                      (unless (location= result default)
                        (inst ,move-inst result default))
                      (let ((ea (ea (* ,bytes-per-element (+ index addend)) sap)))
                        (inst ,expand-inst result ea mask 0)))))))))

      (def-compress-expand-memory-vops f32.16 single-avx512-reg m32.16 vcompressps-masked vexpandps-masked vmovaps f32vec 4)
      (def-compress-expand-memory-vops f64.8  double-avx512-reg m64.8  vcompresspd-masked vexpandpd-masked vmovapd f64vec 8)
      (def-compress-expand-memory-vops u32.16 int-avx512-reg    m32.16 vpcompressd-masked vpexpandd-masked vmovdqa32 u32vec 4)
      (def-compress-expand-memory-vops s32.16 int-avx512-reg    m32.16 vpcompressd-masked vpexpandd-masked vmovdqa32 s32vec 4)
      (def-compress-expand-memory-vops u64.8  int-avx512-reg    m64.8  vpcompressq-masked vpexpandq-masked vmovdqa64 u64vec 8)
      (def-compress-expand-memory-vops s64.8  int-avx512-reg    m64.8  vpcompressq-masked vpexpandq-masked vmovdqa64 s64vec 8)))

;; Neon
#+arm64
(progn
 (define-custom-vop sb-simd-neon::f32!-from-p128
     (:args (src :scs (single-neon-reg) :to :save))
   (:results (dst :scs (single-reg)))
   (:generator
    (inst movi dst 0 :4s)
    (inst dup dst src nil 0)))

 (define-custom-vop sb-simd-neon::f32.4!-from-f32
     (:args (src :scs (single-reg) :target dst))
   (:results (dst :scs (single-neon-reg)))
   (:generator
    (unless (location= src dst)
      (inst ins dst 0 src 0 :s))))

 (define-custom-vop sb-simd-neon:f32.4-dup
     (:args (src :scs (single-neon-reg)))
   (:info lane)
   (:results (dst :scs (single-neon-reg)))
   (:generator
    (inst dup dst src :4s lane)))

 (define-custom-vop sb-simd-neon:f32.4-lane-extract
     (:args (src :scs (single-neon-reg)))
   (:info lane)
   (:results (dst :scs (single-reg)))
   (:generator
    (unless (and (location= dst src)
                 (eql lane 0))
      (inst dup dst src nil lane))))

 (define-custom-vop sb-simd-neon:f32.4-lane-insert
     (:args (src1 :scs (single-neon-reg) :target dst)
            (src2 :scs (single-reg) :to :save))
   (:info lane)
   (:results (dst :scs (single-neon-reg)))
   (:generator
    (unless (location= dst src1)
      (inst mov dst src1 :16b))
    (inst ins dst lane
          (make-random-tn (sc-or-lose 'single-neon-reg) (tn-offset src2)) 0
          :s)))

 (define-custom-vop sb-simd-neon:f32.4-ins
     (:args (src1 :scs (single-neon-reg) :target dst)
            (src2 :scs (single-neon-reg) :to :save))
   (:info idx1 idx2)
   (:results (dst :scs (single-neon-reg)))
   (:generator
    (unless (location= dst src1)
      (inst mov dst src1 :16b))
    (inst ins dst idx1 src2 idx2 :s)))

 (define-custom-vop sb-simd-neon::f64!-from-p128
     (:args (src :scs (double-neon-reg) :to :save))
   (:results (dst :scs (double-reg)))
   (:generator
    (inst movi dst 0 :2d)
    (inst dup dst src nil 0)))

 (define-custom-vop sb-simd-neon::f64.2!-from-f64
     (:args (src :scs (double-reg) :target dst))
   (:results (dst :scs (double-neon-reg)))
   (:generator
    (unless (location= src dst)
      (inst ins dst 0 src 0 :d))))

 (define-custom-vop sb-simd-neon:f64.2-dup
     (:args (src :scs (double-neon-reg)))
   (:info lane)
   (:results (dst :scs (double-neon-reg)))
   (:generator
    (inst dup dst src :2d lane)))

 (define-custom-vop sb-simd-neon:f64.2-lane-extract
     (:args (src :scs (double-neon-reg)))
   (:info lane)
   (:results (dst :scs (double-reg)))
   (:generator
    (inst dup dst src nil lane)))

 (define-custom-vop sb-simd-neon:f64.2-lane-insert
     (:args (src1 :scs (double-neon-reg) :target dst)
            (src2 :scs (double-reg) :to :save))
   (:info lane)
   (:results (dst :scs (double-neon-reg)))
   (:generator
    (unless (location= dst src1)
      (inst mov dst src1 :16b))
    (inst ins dst lane
          (make-random-tn (sc-or-lose 'single-neon-reg) (tn-offset src2)) 0
          :d)))

 (define-custom-vop sb-simd-neon:f64.2-ins
     (:args (src1 :scs (double-neon-reg) :target dst)
            (src2 :scs (double-neon-reg) :to :save))
   (:info idx1 idx2)
   (:results (dst :scs (double-neon-reg)))
   (:generator
    (unless (location= dst src1)
      (inst mov dst src1 :16b))
    (inst ins dst idx1 src2 idx2 :d)))

 (define-custom-vop sb-simd-neon:u8.16-shuffle
     (:args (src1 :scs (single-neon-reg))
            (control :scs (single-neon-reg)))
   (:results (dst :scs (single-neon-reg)))
   (:generator
    (inst tbl dst (list src1) control :16b)))

 (macrolet
     ((def (sign width count)
        (multiple-value-bind (arrangement partial-arrangement smaller-arrangement smaller-partial-arrangement larger-arrangement element)
            (ecase width
              (8 (values :16b :8b nil nil :8h :b))
              (16 (values :8h :4h :16b :8b :4s :h))
              (32 (values :4s :2s :8h :4h :2d :s))
              (64 (values :2d nil :4s :2s nil :d)))
          (let ((smaller-width (/ width 2))
                (smaller-count (* count 2))
                (scalar-reg (if (eql sign :s) 'signed-reg 'unsigned-reg)))
            (flet ((name (format-control &rest format-arguments)
                     (intern (apply #'format nil format-control format-arguments)
                             (find-package :sb-simd-neon))))
              `(progn
                 (define-custom-vop ,(name "~a~d.~d!-FROM-~a~a" sign width count sign width)
                     (:args (src :scs (,scalar-reg) :target dst))
                   (:results (dst :scs (int-neon-reg)))
                   (:generator
                    (inst fmov (make-random-tn (sc-or-lose ',(if (eql width 64) 'double-reg 'single-reg)) (tn-offset dst)) src)))
                 (define-custom-vop ,(name "~a~d.~d-DUP" sign width count)
                     (:args (src :scs (int-neon-reg)))
                   (:info lane)
                   (:results (dst :scs (int-neon-reg)))
                   (:generator
                    (inst dup dst src ,arrangement lane)))
                 (define-custom-vop ,(name "~a~d.~d-LANE-EXTRACT" sign width count)
                     (:args (src :scs (int-neon-reg)))
                   (:info lane)
                   (:results (dst :scs (,scalar-reg)))
                   (:generator
                    (inst ,(if (and (eql sign :s) (not (eql width 64)))
                               'smov
                               'umov)
                          dst src lane ,element)))
                 (define-custom-vop ,(name "~a~d.~d-LANE-INSERT" sign width count)
                     (:args (src1 :scs (int-neon-reg) :target dst)
                            (src2 :scs (,scalar-reg) :to :save))
                   (:info lane)
                   (:results (dst :scs (int-neon-reg)))
                   (:generator
                    (unless (location= dst src1)
                      (inst mov dst src1 :16b))
                    (inst ins dst lane src2 nil ,element)))
                 (define-custom-vop ,(name "~a~d.~d-INS" sign width count)
                     (:args (src1 :scs (int-neon-reg) :target dst)
                            (src2 :scs (int-neon-reg) :to :save))
                   (:info idx1 idx2)
                   (:results (dst :scs (int-neon-reg)))
                   (:generator
                    (unless (location= dst src1)
                      (inst mov dst src1 :16b))
                    (inst ins dst idx1 src2 idx2 ,element)))
                 ;; Conversion from the smaller type.
                 ,@(when smaller-arrangement
                     `((define-custom-vop ,(name "~a~d.~d-FROM-~a~d.~d" sign width count sign smaller-width smaller-count)
                           (:args (src :scs (int-neon-reg)))
                         (:results (dst :scs (int-neon-reg)))
                         (:generator
                          (inst ,(if (eql sign :s) 'sshll 'ushll) dst ,arrangement src ,smaller-partial-arrangement)))
                       (define-custom-vop ,(name "~a~d.~d-FROM-~a~d.~d-HI" sign width count sign smaller-width smaller-count)
                           (:args (src :scs (int-neon-reg)))
                         (:results (dst :scs (int-neon-reg)))
                         (:generator
                          (inst ,(if (eql sign :s) 'sshll2 'ushll2) dst ,arrangement src ,smaller-arrangement)))))
                 (define-custom-vop ,(name "~a~d.~d-SHIFTR" sign width count)
                     (:args (src :scs (int-neon-reg)))
                   (:info shift)
                   (:results (dst :scs (int-neon-reg)))
                   (:generator
                    (inst ,(if (eql sign :s) 'sshr 'ushr) dst src shift ,arrangement)))
                 (define-custom-vop ,(name "~a~d.~d-SHIFTL" sign width count)
                     (:args (src :scs (int-neon-reg)))
                   (:info shift)
                   (:results (dst :scs (int-neon-reg)))
                   (:generator
                    (inst shl dst src shift ,arrangement)))
                 ,@(when larger-arrangement
                     `((define-custom-vop ,(name "~a~d.~d-SHIFTL-LONG" sign width count)
                           (:args (src :scs (int-neon-reg)))
                         (:info shift)
                         (:results (dst :scs (int-neon-reg)))
                         (:generator
                          (inst ,(if (eql sign :s) 'sshll 'ushll) dst ,larger-arrangement src ,partial-arrangement shift)))
                       (define-custom-vop ,(name "~a~d.~d-SHIFTL-LONG-HI" sign width count)
                           (:args (src :scs (int-neon-reg)))
                         (:info shift)
                         (:results (dst :scs (int-neon-reg)))
                         (:generator
                          (inst ,(if (eql sign :s) 'sshll2 'ushll2) dst ,larger-arrangement src ,arrangement shift)))))))))))
   (def :u 8 16)
   (def :u 16 8)
   (def :u 32 4)
   (def :u 64 2)
   (def :s 8 16)
   (def :s 16 8)
   (def :s 32 4)
   (def :s 64 2)))
)
