(in-package #:sb-simd-internals)

(macrolet
    ((define-vref (name kind)
       (with-accessors ((name vref-record-name)
                        (instruction-set vref-record-instruction-set)
                        (value-record vref-record-value-record)
                        (vector-record vref-record-vector-record)
                        (vop vref-record-vop)
                        (sap vref-record-sap-ref))
           (find-function-record name)
         (let* ((simd-width (value-record-simd-width value-record))
                (element-type
                  (second
                   (value-record-type vector-record)))
                (sap-vop (when sap (mksym (symbol-package name) (if (eq kind :store) "%SET-" "%") sap))))
           (declare (ignorable simd-width element-type))
           (ecase kind
             (:load
              (if (not (instruction-set-available-p instruction-set))
                  `(progn
                     (define-missing-instruction ,name
                       :required-arguments (array index))
                     ,@(when sap
                         `((define-missing-instruction ,sap
                             :required-arguments (sap index)))))
                  `(progn
                    (define-inline ,name (array index)
                       (declare (type (array ,element-type) array)
                                (index index))
                       (sb-kernel:check-bound array (array-total-size array) (+ index ,(1- simd-width)))
                       (multiple-value-bind (vector index)
                           (sb-kernel:%data-vector-and-index array index)
                         (declare (type (simple-array ,element-type (*)) vector))
                         (,vop vector index 0)))
                    ,@(when sap
                        `((define-inline ,sap (sap index)
                            (declare (type sb-alien:system-area-pointer sap) (type index index))
                            (,sap-vop sap index 0)))))))
             (:store
              (if (not (instruction-set-available-p instruction-set))
                  `(progn
                     (define-missing-instruction ,name
                       :required-arguments (value array index))
                     ,@(when sap
                         `((define-missing-instruction (setf ,sap)
                             :required-arguments (value sap index)))))
                  `(progn
                    (define-inline ,name (value array index)
                       (declare (type (array ,element-type) array)
                                (index index))
                       (sb-kernel:check-bound array (array-total-size array) (+ index ,(1- simd-width)))
                       (multiple-value-bind (vector index)
                           (sb-kernel:%data-vector-and-index array index)
                         (declare (type (simple-array ,element-type (*)) vector))
                         (,vop (,(value-record-name value-record) value) vector
                               index 0)))
                    ,@(when sap
                        `((define-inline (setf ,sap) (value sap index)
                            (declare (type sb-alien:system-area-pointer sap) (type index index))
                            (,sap-vop (,(value-record-name value-record) value) sap index 0)))))))))))
     (define-vrefs ()
       `(progn
          ,@(loop for load-record in (filter-function-records #'load-record-p)
                  for name = (load-record-name load-record)
                  for sap = (vref-record-sap-ref load-record)
                  collect `(define-vref ,name :load))
          ,@(loop for store-record in (filter-function-records #'store-record-p)
                  for name = (store-record-name store-record)
                  for sap = (vref-record-sap-ref store-record)
                  collect `(define-vref ,name :store)))))
  (define-vrefs))

#+x86-64
(macrolet
    ((def-masked-vref (type element-type mask-type)
       (let* ((pkg (find-package "SB-SIMD-AVX512F"))
              (load-z-name     (mksym pkg type "-LOAD-MASKED-Z"))
              (load-m-name     (mksym pkg type "-LOAD-MASKED"))
              (store-name      (mksym pkg type "-STORE-MASKED"))
              (sap-load-z-name (mksym pkg type "-SAP-REF-MASKED-Z"))
              (sap-load-m-name (mksym pkg type "-SAP-REF-MASKED"))
              (vop-load-z      (mksym pkg "%" type "-LOAD-MASKED-Z"))
              (vop-load-m      (mksym pkg "%" type "-LOAD-MASKED"))
              (vop-store       (mksym pkg "%" type "-STORE-MASKED"))
              (vop-sap-load-z  (mksym pkg "%" type "-SAP-REF-MASKED-Z"))
              (vop-sap-load-m  (mksym pkg "%" type "-SAP-REF-MASKED"))
              (vop-sap-store   (mksym pkg "%SET-" type "-SAP-REF-MASKED"))
              (type-cast       (mksym pkg type))
              (mask-cast       (mksym pkg mask-type)))
         (if (not (instruction-set-available-p (find-instruction-set :avx512f)))
             `(progn
                (defun ,load-z-name (mask array index)
                  (declare (ignore mask array index))
                  (error "AVX512F instruction ~S not supported." ',load-z-name))
                (defun ,load-m-name (mask default array index)
                  (declare (ignore mask default array index))
                  (error "AVX512F instruction ~S not supported." ',load-m-name))
                (defun ,store-name (mask value array index)
                  (declare (ignore mask value array index))
                  (error "AVX512F instruction ~S not supported." ',store-name))
                (defun ,sap-load-z-name (mask sap index)
                  (declare (ignore mask sap index))
                  (error "AVX512F instruction ~S not supported." ',sap-load-z-name))
                (defun ,sap-load-m-name (mask default sap index)
                  (declare (ignore mask default sap index))
                  (error "AVX512F instruction ~S not supported." ',sap-load-m-name))
                (defun (setf ,sap-load-m-name) (value mask sap index)
                  (declare (ignore value mask sap index))
                  (error "AVX512F instruction ~S not supported." '(setf ,sap-load-m-name)))
                (defun (setf ,sap-load-z-name) (value mask sap index)
                  (declare (ignore value mask sap index))
                  (error "AVX512F instruction ~S not supported." '(setf ,sap-load-z-name))))
             `(progn
                ;; Zeroing load
                (define-inline ,load-z-name (mask array index)
                  (declare (type (array ,element-type) array)
                           (type index index))
                  (let ((int-mask (if (integerp mask) mask (mask-value mask))))
                    (when (plusp int-mask)
                      (sb-kernel:check-bound array (array-total-size array) (+ index (1- (integer-length int-mask))))))
                  (multiple-value-bind (vector index)
                      (sb-kernel:%data-vector-and-index array index)
                    (declare (type (simple-array ,element-type (*)) vector))
                    (,vop-load-z (,mask-cast mask) vector index 0)))

                ;; Merging load
                (define-inline ,load-m-name (mask default array index)
                  (declare (type (array ,element-type) array)
                           (type index index))
                  (let ((int-mask (if (integerp mask) mask (mask-value mask))))
                    (when (plusp int-mask)
                      (sb-kernel:check-bound array (array-total-size array) (+ index (1- (integer-length int-mask))))))
                  (multiple-value-bind (vector index)
                      (sb-kernel:%data-vector-and-index array index)
                    (declare (type (simple-array ,element-type (*)) vector))
                    (,vop-load-m (,mask-cast mask) (,type-cast default) vector index 0)))

                ;; Masked store
                (define-inline ,store-name (mask value array index)
                  (declare (type (array ,element-type) array)
                           (type index index))
                  (let ((int-mask (if (integerp mask) mask (mask-value mask))))
                    (when (plusp int-mask)
                      (sb-kernel:check-bound array (array-total-size array) (+ index (1- (integer-length int-mask))))))
                  (multiple-value-bind (vector index)
                      (sb-kernel:%data-vector-and-index array index)
                    (declare (type (simple-array ,element-type (*)) vector))
                    (,vop-store (,mask-cast mask) (,type-cast value) vector index 0)))

                ;; SAP zeroing load
                (define-inline ,sap-load-z-name (mask sap index)
                  (declare (type sb-alien:system-area-pointer sap)
                           (type index index))
                  (,vop-sap-load-z (,mask-cast mask) sap index 0))

                ;; SAP merging load
                (define-inline ,sap-load-m-name (mask default sap index)
                  (declare (type sb-alien:system-area-pointer sap)
                           (type index index))
                  (,vop-sap-load-m (,mask-cast mask) (,type-cast default) sap index 0))

                ;; SAP store: (setf (<type>-sap-ref-masked mask sap index) value)
                (define-inline (setf ,sap-load-m-name) (value mask sap index)
                  (declare (type sb-alien:system-area-pointer sap)
                           (type index index))
                  (,vop-sap-store (,mask-cast mask) (,type-cast value) sap index 0))

                ;; SAP store alias: (setf (<type>-sap-ref-masked-z mask sap index) value)
                (define-inline (setf ,sap-load-z-name) (value mask sap index)
                  (declare (type sb-alien:system-area-pointer sap)
                           (type index index))
                  (,vop-sap-store (,mask-cast mask) (,type-cast value) sap index 0)))))))
  (def-masked-vref f32.16 single-float          m32.16)
  (def-masked-vref f64.8  double-float          m64.8)
  (def-masked-vref u32.16 (unsigned-byte 32)    m32.16)
  (def-masked-vref s32.16 (signed-byte 32)      m32.16)
  (def-masked-vref u64.8  (unsigned-byte 64)    m64.8)
  (def-masked-vref s64.8  (signed-byte 64)      m64.8))

#+x86-64
(macrolet
    ((def-compress-expand-refs (type element-type mask-type)
       (let* ((pkg (find-package "SB-SIMD-AVX512F"))
              (c-store-name         (mksym pkg type "-COMPRESS-STORE"))
              (c-sap-store-name     (mksym pkg type "-SAP-COMPRESS-STORE"))
              (e-load-z-name        (mksym pkg type "-EXPAND-LOAD-Z"))
              (e-sap-load-z-name    (mksym pkg type "-SAP-EXPAND-LOAD-Z"))
              (e-load-m-name        (mksym pkg type "-EXPAND-LOAD"))
              (e-sap-load-m-name    (mksym pkg type "-SAP-EXPAND-LOAD"))
              (vop-c-store          (mksym pkg "%" type "-COMPRESS-STORE"))
              (vop-c-sap-store      (mksym pkg "%" type "-SAP-COMPRESS-STORE"))
              (vop-e-load-z         (mksym pkg "%" type "-EXPAND-LOAD-Z"))
              (vop-e-sap-load-z     (mksym pkg "%" type "-SAP-EXPAND-LOAD-Z"))
              (vop-e-load-m         (mksym pkg "%" type "-EXPAND-LOAD"))
              (vop-e-sap-load-m     (mksym pkg "%" type "-SAP-EXPAND-LOAD"))
              (type-cast            (mksym pkg type))
              (mask-cast            (mksym pkg mask-type)))
         (if (not (instruction-set-available-p (find-instruction-set :avx512f)))
             `(progn
                (defun ,c-store-name (mask value array index)
                  (declare (ignore mask value array index))
                  (error "AVX512F instruction ~S not supported." ',c-store-name))
                (defun (setf ,c-store-name) (value mask array index)
                  (declare (ignore value mask array index))
                  (error "AVX512F instruction ~S not supported." '(setf ,c-store-name)))
                (defun ,c-sap-store-name (mask value sap index)
                  (declare (ignore mask value sap index))
                  (error "AVX512F instruction ~S not supported." ',c-sap-store-name))
                (defun (setf ,c-sap-store-name) (value mask sap index)
                  (declare (ignore value mask sap index))
                  (error "AVX512F instruction ~S not supported." '(setf ,c-sap-store-name)))
                (defun ,e-load-z-name (mask array index)
                  (declare (ignore mask array index))
                  (error "AVX512F instruction ~S not supported." ',e-load-z-name))
                (defun ,e-sap-load-z-name (mask sap index)
                  (declare (ignore mask sap index))
                  (error "AVX512F instruction ~S not supported." ',e-sap-load-z-name))
                (defun ,e-load-m-name (mask default array index)
                  (declare (ignore mask default array index))
                  (error "AVX512F instruction ~S not supported." ',e-load-m-name))
                (defun ,e-sap-load-m-name (mask default sap index)
                  (declare (ignore mask default sap index))
                  (error "AVX512F instruction ~S not supported." ',e-sap-load-m-name)))
             `(progn
                ;; 1. Memory compress store (Array)
                (define-inline ,c-store-name (mask value array index)
                  (declare (type (array ,element-type) array)
                           (type index index))
                  (let ((int-mask (if (integerp mask) mask (mask-value mask))))
                    (when (plusp (logcount int-mask))
                      (sb-kernel:check-bound array (array-total-size array) (+ index (1- (logcount int-mask))))))
                  (multiple-value-bind (vector index)
                      (sb-kernel:%data-vector-and-index array index)
                    (declare (type (simple-array ,element-type (*)) vector))
                    (,vop-c-store (,mask-cast mask) (,type-cast value) vector index 0)))

                (define-inline (setf ,c-store-name) (value mask array index)
                  (declare (type (array ,element-type) array)
                           (type index index))
                  (,c-store-name mask value array index))

                ;; 2. Memory compress store (SAP)
                (define-inline ,c-sap-store-name (mask value sap index)
                  (declare (type sb-alien:system-area-pointer sap)
                           (type index index))
                  (,vop-c-sap-store (,mask-cast mask) (,type-cast value) sap index 0))

                (define-inline (setf ,c-sap-store-name) (value mask sap index)
                  (declare (type sb-alien:system-area-pointer sap)
                           (type index index))
                  (,c-sap-store-name mask value sap index))

                ;; 3. Memory expand load zeroing (Array)
                (define-inline ,e-load-z-name (mask array index)
                  (declare (type (array ,element-type) array)
                           (type index index))
                  (let ((int-mask (if (integerp mask) mask (mask-value mask))))
                    (when (plusp (logcount int-mask))
                      (sb-kernel:check-bound array (array-total-size array) (+ index (1- (logcount int-mask))))))
                  (multiple-value-bind (vector index)
                      (sb-kernel:%data-vector-and-index array index)
                    (declare (type (simple-array ,element-type (*)) vector))
                    (,vop-e-load-z (,mask-cast mask) vector index 0)))

                ;; 4. Memory expand load zeroing (SAP)
                (define-inline ,e-sap-load-z-name (mask sap index)
                  (declare (type sb-alien:system-area-pointer sap)
                           (type index index))
                  (,vop-e-sap-load-z (,mask-cast mask) sap index 0))

                ;; 5. Memory expand load merging (Array)
                (define-inline ,e-load-m-name (mask default array index)
                  (declare (type (array ,element-type) array)
                           (type index index))
                  (let ((int-mask (if (integerp mask) mask (mask-value mask))))
                    (when (plusp (logcount int-mask))
                      (sb-kernel:check-bound array (array-total-size array) (+ index (1- (logcount int-mask))))))
                  (multiple-value-bind (vector index)
                      (sb-kernel:%data-vector-and-index array index)
                    (declare (type (simple-array ,element-type (*)) vector))
                    (,vop-e-load-m (,mask-cast mask) (,type-cast default) vector index 0)))

                ;; 6. Memory expand load merging (SAP)
                (define-inline ,e-sap-load-m-name (mask default sap index)
                  (declare (type sb-alien:system-area-pointer sap)
                           (type index index))
                  (,vop-e-sap-load-m (,mask-cast mask) (,type-cast default) sap index 0)))))))
  (def-compress-expand-refs f32.16 single-float          m32.16)
  (def-compress-expand-refs f64.8  double-float          m64.8)
  (def-compress-expand-refs u32.16 (unsigned-byte 32)    m32.16)
  (def-compress-expand-refs s32.16 (signed-byte 32)      m32.16)
  (def-compress-expand-refs u64.8  (unsigned-byte 64)    m64.8)
  (def-compress-expand-refs s64.8  (signed-byte 64)      m64.8))

#+x86-64
(macrolet
    ((def-broadcast-refs (type element-type mask-type)
       (let* ((pkg (find-package "SB-SIMD-AVX512F"))
              (bc-name           (mksym pkg type "-BROADCAST-AREF"))
              (bc-z-name         (mksym pkg type "-BROADCAST-AREF-MASKED-Z"))
              (bc-m-name         (mksym pkg type "-BROADCAST-AREF-MASKED"))
              (sap-bc-name       (mksym pkg type "-BROADCAST-SAP-REF"))
              (sap-bc-z-name     (mksym pkg type "-BROADCAST-SAP-REF-MASKED-Z"))
              (sap-bc-m-name     (mksym pkg type "-BROADCAST-SAP-REF-MASKED"))

              (vop-bc            (mksym pkg "%" type "-BROADCAST-AREF"))
              (vop-bc-z          (mksym pkg "%" type "-BROADCAST-AREF-MASKED-Z"))
              (vop-bc-m          (mksym pkg "%" type "-BROADCAST-AREF-MASKED"))
              (vop-sap-bc        (mksym pkg "%" type "-BROADCAST-SAP-REF"))
              (vop-sap-bc-z      (mksym pkg "%" type "-BROADCAST-SAP-REF-MASKED-Z"))
              (vop-sap-bc-m      (mksym pkg "%" type "-BROADCAST-SAP-REF-MASKED"))

              (type-cast         (mksym pkg type))
              (mask-cast         (mksym pkg mask-type))
              (broadcast-sym     (mksym pkg type "-BROADCAST")))
         (if (not (instruction-set-available-p (find-instruction-set :avx512f)))
             `(progn
                (defun ,bc-name (array &rest indices)
                  (declare (ignore array indices))
                  (error "AVX512F instruction ~S not supported." ',bc-name))
                (defun ,bc-z-name (mask array &rest indices)
                  (declare (ignore mask array indices))
                  (error "AVX512F instruction ~S not supported." ',bc-z-name))
                (defun ,bc-m-name (mask default array &rest indices)
                  (declare (ignore mask default array indices))
                  (error "AVX512F instruction ~S not supported." ',bc-m-name))
                (defun ,sap-bc-name (sap index)
                  (declare (ignore sap index))
                  (error "AVX512F instruction ~S not supported." ',sap-bc-name))
                (defun ,sap-bc-z-name (mask sap index)
                  (declare (ignore mask sap index))
                  (error "AVX512F instruction ~S not supported." ',sap-bc-z-name))
                (defun ,sap-bc-m-name (mask default sap index)
                  (declare (ignore mask default sap index))
                  (error "AVX512F instruction ~S not supported." ',sap-bc-m-name)))
             `(progn
                ;; 1. Unmasked broadcast from array
                (defun ,bc-name (array &rest indices)
                  (declare (type (array ,element-type) array))
                  (let ((idx (if (= (length indices) 1)
                                 (first indices)
                                 (apply #'array-row-major-index array indices))))
                    (declare (type index idx))
                    (sb-kernel:check-bound array (array-total-size array) idx)
                    (multiple-value-bind (vector index)
                        (sb-kernel:%data-vector-and-index array idx)
                      (declare (type (simple-array ,element-type (*)) vector))
                      (,vop-bc vector index 0))))

                (define-compiler-macro ,bc-name (array &rest indices)
                  (if (= (length indices) 1)
                      (let ((arr (gensym "ARR"))
                            (idx (gensym "IDX"))
                            (vec (gensym "VEC"))
                            (vidx (gensym "VIDX")))
                        `(let ((,arr ,array)
                               (,idx ,(first indices)))
                           (declare (type (array ,',element-type) ,arr)
                                    (type index ,idx))
                           (sb-kernel:check-bound ,arr (array-total-size ,arr) ,idx)
                           (multiple-value-bind (,vec ,vidx)
                               (sb-kernel:%data-vector-and-index ,arr ,idx)
                             (declare (type (simple-array ,',element-type (*)) ,vec))
                             (,',vop-bc ,vec ,vidx 0))))
                      `(,',bc-name ,array (apply #'array-row-major-index ,array ,@indices))))

                ;; 2. Unmasked broadcast from SAP
                (define-inline ,sap-bc-name (sap index)
                  (declare (type sb-alien:system-area-pointer sap)
                           (type index index))
                  (,vop-sap-bc sap index 0))

                ;; 3. Masked-Z broadcast from array
                (defun ,bc-z-name (mask array &rest indices)
                  (declare (type (array ,element-type) array))
                  (let ((idx (if (= (length indices) 1)
                                 (first indices)
                                 (apply #'array-row-major-index array indices))))
                    (declare (type index idx))
                    (let ((int-mask (if (integerp mask) mask (mask-value mask))))
                      (when (plusp int-mask)
                        (sb-kernel:check-bound array (array-total-size array) idx)))
                    (multiple-value-bind (vector index)
                        (sb-kernel:%data-vector-and-index array idx)
                      (declare (type (simple-array ,element-type (*)) vector))
                      (,vop-bc-z (,mask-cast mask) vector index 0))))

                (define-compiler-macro ,bc-z-name (mask array &rest indices)
                  (if (= (length indices) 1)
                      (let ((m (gensym "MASK"))
                            (arr (gensym "ARR"))
                            (idx (gensym "IDX"))
                            (vec (gensym "VEC"))
                            (vidx (gensym "VIDX"))
                            (im (gensym "INT-MASK")))
                        `(let ((,m ,mask)
                               (,arr ,array)
                               (,idx ,(first indices)))
                           (declare (type (array ,',element-type) ,arr)
                                    (type index ,idx))
                           (let ((,im (if (integerp ,m) ,m (mask-value ,m))))
                             (when (plusp ,im)
                               (sb-kernel:check-bound ,arr (array-total-size ,arr) ,idx)))
                           (multiple-value-bind (,vec ,vidx)
                               (sb-kernel:%data-vector-and-index ,arr ,idx)
                             (declare (type (simple-array ,',element-type (*)) ,vec))
                             (,',vop-bc-z (,',mask-cast ,m) ,vec ,vidx 0))))
                      `(,',bc-z-name ,mask ,array (apply #'array-row-major-index ,array ,@indices))))

                ;; 4. Masked-Z broadcast from SAP
                (define-inline ,sap-bc-z-name (mask sap index)
                  (declare (type sb-alien:system-area-pointer sap)
                           (type index index))
                  (,vop-sap-bc-z (,mask-cast mask) sap index 0))

                ;; 5. Masked Merging broadcast from array
                (defun ,bc-m-name (mask default array &rest indices)
                  (declare (type (array ,element-type) array))
                  (let ((idx (if (= (length indices) 1)
                                 (first indices)
                                 (apply #'array-row-major-index array indices))))
                    (declare (type index idx))
                    (let ((int-mask (if (integerp mask) mask (mask-value mask))))
                      (when (plusp int-mask)
                        (sb-kernel:check-bound array (array-total-size array) idx)))
                    (multiple-value-bind (vector index)
                        (sb-kernel:%data-vector-and-index array idx)
                      (declare (type (simple-array ,element-type (*)) vector))
                      (,vop-bc-m (,mask-cast mask) (,type-cast default) vector index 0))))

                (define-compiler-macro ,bc-m-name (mask default array &rest indices)
                  (if (= (length indices) 1)
                      (let ((m (gensym "MASK"))
                            (d (gensym "DEF"))
                            (arr (gensym "ARR"))
                            (idx (gensym "IDX"))
                            (vec (gensym "VEC"))
                            (vidx (gensym "VIDX"))
                            (im (gensym "INT-MASK")))
                        `(let ((,m ,mask)
                               (,d ,default)
                               (,arr ,array)
                               (,idx ,(first indices)))
                           (declare (type (array ,',element-type) ,arr)
                                    (type index ,idx))
                           (let ((,im (if (integerp ,m) ,m (mask-value ,m))))
                             (when (plusp ,im)
                               (sb-kernel:check-bound ,arr (array-total-size ,arr) ,idx)))
                           (multiple-value-bind (,vec ,vidx)
                               (sb-kernel:%data-vector-and-index ,arr ,idx)
                             (declare (type (simple-array ,',element-type (*)) ,vec))
                             (,',vop-bc-m (,',mask-cast ,m) (,',type-cast ,d) ,vec ,vidx 0))))
                      `(,',bc-m-name ,mask ,default ,array (apply #'array-row-major-index ,array ,@indices))))

                ;; 6. Masked Merging broadcast from SAP
                (define-inline ,sap-bc-m-name (mask default sap index)
                  (declare (type sb-alien:system-area-pointer sap)
                           (type index index))
                  (,vop-sap-bc-m (,mask-cast mask) (,type-cast default) sap index 0))

                ;; Compiler macro for (<type>-broadcast (aref ...))
                (define-compiler-macro ,broadcast-sym (&whole form arg)
                  (cond
                    ((and (consp arg) (eq (first arg) 'aref))
                     `(,',bc-name ,@(rest arg)))
                    ((and (consp arg) (eq (first arg) 'row-major-aref))
                     `(,',bc-name ,@(rest arg)))
                    (t form))))))))
  (def-broadcast-refs f32.16 single-float          m32.16)
  (def-broadcast-refs f64.8  double-float          m64.8)
  (def-broadcast-refs u32.16 (unsigned-byte 32)    m32.16)
  (def-broadcast-refs s32.16 (signed-byte 32)      m32.16)
  (def-broadcast-refs u64.8  (unsigned-byte 64)    m64.8)
  (def-broadcast-refs s64.8  (signed-byte 64)      m64.8))



